- .gitignore
- dist/commonjs/File.js
- src/File.ts
- Added exports.default to .html file format
> Added exports.default to .html file format

- README.md
Provide more details on how to retrieve back the dynamic module
> Dynamic module

- README.md
Hey,
I fixed the link to your gitter channel, there is a typo. 
Very promising project 👍
Greetings, René
> Fix link to gitter channel 

- package.json
as advised by https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
> typescript - mark the "types" property

- .gitignore
- .npmignore
- docs/devserver.md
Later: will also PR other places which are relative to `process.cwd` once this is merged :rose:
> :memo: documentation improvements

- docs/configuration.md
> :memo: configuration paths clarity :rose:

- src/tslint.json
Don't think its used as it currently has 662 errors. Removing the options that are giving the errors :rose:
> cleanup tslint

- docs/builtin-plugins.md
- docs/configuration.md
- docs/typescript.md
Helps make it easier to learn configuring typescript :rose:
> tsconfig customization

- docs/bundle.md
- formatting cleanups 
- Mention that bundle inputs are relative to `homeDir` 
- mention that outFiles if used is relative to `process.cwd()`
Thanks! :rose:
> :memo: improve bundling docs

- .editorconfig
- docs/bundle.md
- docs/configuration.md
- docs/devserver.md
- docs/typescript.md
- src/FuseBox.ts
- src/Utils.ts
- src/WorkflowContext.ts
- src/devServer/HTTPServer.ts
- src/devServer/Server.ts
- src/plugins/HotReloadPlugin.ts
> more documentation

- docs/configuration.md
subj.
I also added explicit mention of fuse-box creating directory structure for `Out File`
**UPD:** Sorry, my editor takes care of trailing whitespaces. Let me know if you mind it
> docs: Correct Home Directory being relatieve to AppRoot

- modules/fuse-box-loader-api/fusebox.js
- src/WorkflowContext.ts
- src/loader/LoaderAPI.ts
- src/plugins/HotReloadPlugin.ts
Just the code cleanups from https://github.com/fuse-box/fuse-box/pull/158 so that PR becomes easier to review :rose:
> :memo: code cleanups :rose:

- docs/builtin-plugins.md
refs https://github.com/fuse-box/fuse-box/pull/171 :rose:
> :memo: rename to actual plugin name `PostCSS`

- gulpfile.js
- src/loader/LoaderAPI.ts
- src/modules/fsbx-default-css-plugin/index.ts
⚠️ Work in progress. 
So user doesn't need to do this hacky line https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/blob/df23675337e37013b6d8bb9803de0423400b029a/src/client/hmr.ts#L1 :rose:
> Type definitions for loader API

- src/File.ts
Replaced full path in favor of relative path (from `homeDir`).
Ref. #270
> Fix RegExp test subject for plugins to apply

- docs/changelog.md
- docs/configuration.md
- docs/devserver.md
- docs/loader-api.md
- package.json
more on aliasing
more on registering plugins
fixing package description to match docs
links to relevant example projects
linking connected sections
adding approot anchor
formatting
consistency
fixing typos
no emoji =(
> Minor docs improvements

- docs/bundle.md
- docs/plugin-api.md
adding more docs for plugin apis
expanding transformation
adding getting started information about the ast
things to experiment with
plugin api source code
importing and scoping 
adding importing example
adding scoped example
no emoji =(
> plugin transformation ast basic docs, importing and scoping, code links, tips

- docs/tips.md
> Adds some tips on Electron.

- src/arithmetic/Arithmetic.ts
https://github.com/webpack/webpack/pull/1227#issuecomment-120780108
> normalize filename

- src/core/FuseBox.ts
extends https://github.com/fuse-box/fuse-box/pull/392
> cache issue sync on windows only

- src/plugins/stylesheet/CSSplugin.ts
Added some extra type info to CSSPlugin so it's not `any`
> Add typings for CSSPlugin options 🐙

- docs/bundle.md
https://github.com/fuse-box/fuse-box/issues/453
> 🔗 globtester link fix

- src/plugins/VuePlugin.ts
As said in Issue #125 on [this comment](https://github.com/fuse-box/fuse-box/issues/125#issuecomment-298455538)
> Fix VuePlugin

- src/plugins/VuePlugin.ts
https://vuejs.org/v2/guide/installation.html
(see  section "Runtime + Compiler vs. Runtime-only)
By compiling to a render function instead of a template string, users are able to use the smaller runtime version of vuejs.
Largely based on the template compiler of vuejs/vueify.
> Allow the use of smaller vue-runtime by compiling templates

- src/sparky/SparkFlow.ts
- src/sparky/Sparky.ts
- src/tests/sparky/Sparky.test.ts
Also added a test for usage of src() with an array.
> Now src() and watch() both accept an array

- src/plugins/stylesheet/LESSPlugin.ts
Include homeDir to fix relative paths in LESSPlugin
> 491 - Fix LESSPlugin relative path issue

- docs/configuration.md
- docs/getting-started.md
A few tweaks that I made as I was going through each 😄.
> Improvements & typo fixes for `getting-started` & `configuration` docs

- docs/_meta.json
- docs/plugins/misc/UglifyESPlugin.md
- gulpfile.js
- src/index.ts
- src/plugins/UglifyESPlugin.ts
- src/tests/plugins/UglifyESPlugin.test.ts
Created a [UglifyES](https://github.com/mishoo/UglifyJS2/tree/harmony) plugin based on the UglifyJS plugin.
> UglifyESPlugin

- src/Config.ts
I had an issue that I can't write inside our source tree (due to a stupid build system we have) so I can't use fusebox unless we have the possibility to configure the fusebox TEMP folder
> possibility to configure the temp folder

- src/BundleSource.ts
- src/core/BundleSplit.ts
- src/core/UserOutput.ts
- src/core/WorkflowContext.ts
- src/tests/BundleSplit.test.ts
- src/tests/stubs/TestEnvironment.ts
and a WIP test for bundle splitting with a separate test environment for it.
> Small fixes to split bundles, source maps and hashing

- README.md
Links in the "Highlights" section were broken.
> Fix links to fuse-box.org

- docs/plugins/css/SassPlugin.md
- src/plugins/stylesheet/SassPlugin.ts
- src/tests/plugins/SassPlugin.test.ts
Adds support for node-sass' custom functions:
https://github.com/sass/node-sass#functions--v300---experimental
> SassPlugin: support custom functions

- docs/sparky.md
Small typofix for first pull request :)
> Typo in docs/sparky

- modules/url/index.js
This polyfills url with https://github.com/defunctzombie/node-url
> polyfill url

- docs/plugins/transpilers/VuePlugin.md
- gulpfile.js
- src/plugins/VuePlugin.ts
- src/tests/plugins/VuePlugin.test.ts
> Add babel support to VuePlugin

- gulpfile.js
- package.json
Looks like the original intention of dist-commonjs was to produce source maps to help with debugging. This pull request implements that.
> Now dist-commonjs sourcemaps are generated 

- docs/examples-seeds.md
> otheca seed

- docs/quantum.md
Simple typo in docs, code is clearly not 225kb
> change kb to bytes in quantum docs

- src/Utils.ts
- src/quantum/core/ProducerAbstraction.ts
- src/quantum/core/utils.ts
That wasn't too bad. Let me know what you think.
Quantum is pretty neat. Great Work!
> fix: quantum relative package requires

- package.json
- src/analysis/FileAnalysis.ts
Stage 3 feature, already implemented in chrome/FF/node.
> feat: support object rest-spread

- docs/configuration.md
- src/core/File.ts
- src/core/FuseBox.ts
fixes https://github.com/fuse-box/fuse-box/issues/792
> Typescript custom transformers

- docs/configuration.md
- docs/examples-seeds.md
- docs/faq.md
- docs/loader-api.md
- docs/plugins/css/CSSModules.md
- docs/plugins/css/CSSResourcePlugin.md
- docs/plugins/css/PostCSSPlugin.md
- docs/plugins/html/ConsolidatePlugin.md
- docs/plugins/html/MarkdownPlugin.md
- docs/plugins/html/WebIndexPlugin.md
- docs/plugins/misc/PlainJSPlugin.md
- docs/plugins/misc/SourceMapPlainJsPlugin.md
- docs/plugins/transpilers/BabelPlugin.md
- docs/plugins/transpilers/CoffeePlugin.md
- docs/plugins/transpilers/VueComponentPlugin.md
- docs/plugins/transpilers/VuePlugin.md
- docs/quantum.md
Just a few bits of house keeping:
- Updated seeds list to include new Vue.js seed
- Seeds and Examples were all mixed up so I've moved them into correct places
- I've standardised the plugin names to be "Title Casing"
- Updated links to plugins after casing changes above (the spaces mean it would need a hyphon. e.g. Foo Plugin ----> foo-plugin.md
> Documentation Tidy

- package.json
Feel free to close, but please pull this branch down and have a play to see what you think:
- `npm i`
Then do a git commit. Expected message format is `type(scope): short message`, e.g. `feat(bundler): Made the bundler do something cool`. If it doesnt follow this format then it will error.
Let me know what your thoughts are.
The latest version of this PR will accept either of the following commit messages as valid:
- `type(scope): short message`
- `type: short message`
> Commit Message Validation & Formatting

- src/core/FuseBox.ts
This fixes https://github.com/fuse-box/fuse-box/issues/923
> fix: add type to FuseBoxOptions.package

- docs/sparky.md
- src/sparky/SparkyFile.ts
This PR implements a method for changing a file name as part of a Sparky flow.
> feat: Sparky - added a rename function and some documentation

- src/lib/postcss/PostCSSResourcePlugin.ts
fixes https://github.com/fuse-box/fuse-box/issues/980
> fix: Adds border-image CSS prop to CSSResourcePlugin

- docs/plugins/css/CSSModules.md
- src/plugins/stylesheet/CSSModules.ts
This will allow the classes written to the DOM to be user defined, instead of relying on the default in the postcss-modules.
> feature: add scope option to CSSModules plugin

- docs/introduction/install.md
> fix typo "than then"

- docs/introduction/about-plugins.md
> docs: Fix typos

- src/quantum/plugin/BundleWriter.ts
> Fix for uglify es6 option being ignored in quantum

- docs/introduction/getting-started.md
- docs/introduction/install.md
- docs/introduction/production-vs-dev.md
In response to #1018.
I might add more commits while reading through the guide! :)
> Fix some typos/grammatical errors/layouting in the getting started guide.

- src/plugins/RawPlugin.ts
`RawPlugin` now checks if the last changed file was one of the CSS dependencies, and if so doesn't use the cache.  The `WorkflowContext` then takes care of updating the module via HMR automatically.
> fix: RawPlugin respects CSS dependencies for HMR

- docs/sparky/sparky.md
Just some docfixes. Things should be a bit clearer now.
> docs: Sparky udpates

- src/sparky/SparkFlow.ts
- src/sparky/Sparky.ts
Optional callback function for Sparky.watch:
```javascript
Sparky.watch('src/**/**.*', undefined, (event, filePath) => {
fuse.sendPageReload()
}).exec()
```
> Callback function for Sparky.watch

- src/sparky/SparkyUtils.ts
Fix the tsc spawn when runned on windows
> Fix tsc function

- src/sparky/SparkyUtils.ts
Fix the types of arguments
Add missing arguments
Add Watch option
> Fix the definition of TSC options

- docs/development/watching.md
There is something wrong here but i can't figure what.
> Possible typo fix

- gulpfile.js
- package.json
- src/tslint.json
> feat: tslint configuration

- docs/quantum/options.md
- src/quantum/plugin/BundleWriter.ts
- src/quantum/plugin/QuantumOptions.ts
replacement for #1079 (i really need to learn how to revert fork ...)
> feat: bake quantum api into multiple bundles

- src/sparky/index.ts
See [https://basarat.gitbooks.io/typescript/docs/tips/bind.html] for more details
> Fixes #1101 types missing because of using bind

- src/loader/LoaderAPI.ts
Hello, i have make PR for add missing implementation in the source file `LoaderAPI ` of my last PR.
> Fix missing implementation last fix on source LoaderAPI

- docs/development/hmr.md
Otherwise probably people have no idea it is possible when emitHMRDependencies = true.
> Add note on existence of dependants.

- docs/introduction/about-plugins.md
> Fixed spelling of `CSSResourcePlugin`

- src/loader/LoaderAPI.ts
> Closes #1163

- src/analysis/FileAnalysis.ts
- src/core/SourceMapGenerator.ts
- src/loader/LoaderAPI.ts
- src/loader/tsconfig.json
- src/modules/tsconfig.json
- src/plugins/SourceMapPlainJsPlugin.ts
- src/quantum/core/nodes/RequireStatement.ts
- src/tests/ExtensionOverrides.test.ts
- src/tests/fixtures/cases/ts/Hello.ts
- src/tests/fixtures/cases/ts/tsconfig.json
- src/tests/fixtures/tsconfig.json
- src/tests/plugins/BabelPlugin.test.ts
- src/tests/plugins/BublePlugin.test.ts
- src/tests/plugins/CSSPlugin.test.ts
- src/tests/plugins/CoffeePlugin.test.ts
- src/tests/plugins/ConsolidatePlugin.test.ts
- src/tests/plugins/HTMLPlugin.test.ts
- src/tests/plugins/JSONPlugin.test.ts
- src/tests/plugins/MarkdownPlugin.test.ts
- src/tests/plugins/SassPlugin.test.ts
related to #1183
used this command to find the errors `sh -c 'find src -iname tsconfig.json | while read f; do echo "PROJ: $f"; tsc -p "$f" --noEmit --noUnusedLocals false; echo; done'`
the project should have a way of running typescript with typechecking
> fix typescript errors

- src/quantum/core/AstUtils.ts
- src/quantum/core/FileAbstraction.ts
- src/quantum/tests/GlobalVariable.test.ts
> fix: require statements ignored if not 'true' requires. fixes #1142

- docs/plugins/html/ConsolidatePlugin.md
- src/plugins/ConsolidatePlugin.ts
- src/tests/plugins/ConsolidatePlugin.test.ts
> Consolidate: Pass baseDir & includeDir as options

- modules/fuse-box-responsive-api/index.js
- src/loader/LoaderAPI.ts
> fix: syntheticDefaultExportPolyfill Check if frozen before attempting to defineProperty.

- src/plugins/ConsolidatePlugin.ts
> ConsolidatePlugin: Template engine takes basedir not baseDir

- docs/plugins/html/WebIndexPlugin.md
- src/plugins/WebIndexPlugin.ts
Update WebIndexPlugin.ts in order to support the defer boolean attribute in script tags. Thanks
> WebIndexPlugin additional attributes support in script tags

- docs/plugins/css/CSSResourcePlugin.md
Added doc for filesMapping option.
> Updating CSSResourcePlugin doc

- docs/development/configuration.md
- src/core/FuseBox.ts
- src/core/PathMaster.ts
- src/core/WorkflowContext.ts
Fixes https://github.com/fuse-box/fuse-box/issues/817
> added support for arrays in modulesFolder

- src/quantum/plugin/QuantumCore.ts
@nchanged a fast publish to next would be much appreciated! this is breaking my current ie 11 builds
> fix: Global keys order is respected in config, fixes #1304

- docs/quantum/options.md
- src/quantum/plugin/FlatFileGenerator.ts
- src/quantum/plugin/QuantumOptions.ts
- src/quantum/plugin/modifications/EnvironmentConditionModification.ts
https://github.com/fuse-box/fuse-box/issues/1301
note: I did let the old `npm` mode as `npm-server` for backward compatibility.
> 3 npm modes : browser/server/universal

- README.md
Hey, I want to refine the readme a little bit so it's mor user- google- whatever- friendly. I don't consider it finished, but wanted to know your opinion so we can polish it together.
You can find a rendered version here: https://github.com/merlinnot/fuse-box/blob/readme/README.md
I'll definitely change the badges to be consistent, that I've already noticed.
> WIP: docs(README): Refine Readme to be more modern and user friendly

- package.json
- src/quantum/plugin/QuantumBit.ts
- src/tests/dynamic_imports_test/CodeSplittingFileIntegrity.test.ts
> fix(Quantum): Prevent Quantum from creating empty chunks

- src/BundleSource.ts
> fix: #1393

- docs/plugin-api.md
I added a bunch of extra information and updated all the line numbers in the links to current master. This was a big learning experience, thanks for making FuseBox!
> upd doc/plugin-api.md

- docs/getting-started/installation.md
- docs/guides/working-with-targets.md
- docs/plugins/terser.md
- docs/plugins/uglifyes.md
- docs/production-builds/quantum-configuration.md
- docs/production-builds/quantum.md
- package-lock.json
- package.json
- src/Utils.ts
- src/index.ts
- src/plugins/TerserPlugin.ts
- src/quantum/plugin/BundleWriter.ts
- src/quantum/plugin/QuantumPlugin.ts
- src/tests/plugins/TerserPlugin.test.ts
> feat: Add Terser support for minification

- modules/domain/index.js
> Properly export the domain polyfill

- src/index.ts
It is not currently exported :)
> Export Babel7Plugin

- src/core/WorkflowContext.ts
- src/tests/AutoImport.test.ts
Fixes [issues/1474](https://github.com/fuse-box/fuse-box/issues/1474)
> Fix autoImport when target is server

- docs/development/configuration.md
Adds documentation for `emitHMRDependencies`
Related to #1476
> docs: Document emitHMRDependencies

- docs/development/launching.md
- src/FuseProcess.ts
This pull request adds the ability to start the fuseprocess with specified cli Args, so that process.argv gets populated.
> feat: Add ability to pass optional cli Args to FuseProcess

- modules/fuse-box-responsive-api/index.js
- src/tests/QuantumCSSplitting.test.ts
Attends to https://github.com/fuse-box/fuse-box/issues/1444
> move CSS insertion from top of head tag to the bottom

- FuseBox4.0_changelog.md
- docs/development/configuration.md
- src/Utils.ts
- src/analysis/FileAnalysis.ts
- src/analysis/plugins/DynamicImportStatement.ts
- src/analysis/plugins/ImportDeclaration.ts
- src/core/FuseBox.ts
- src/core/TypescriptConfig.ts
- src/core/WorkflowContext.ts
- tests/TypescriptConfig.test.ts
[issues/1480](https://github.com/fuse-box/fuse-box/issues/1480)
> Implementation of tsconfig paths resolution

- src/sparky/sparky_chain.ts
- src/utils/utils.ts
> fix: fixes image corruption on sparky src dest copy

- .gitignore
- .vscode/launch.json
- package-lock.json
- package.json
- playground/monorepo_alt/base-project1-tsconfig.json
- playground/monorepo_alt/base-project2-tsconfig.json
- playground/monorepo_alt/packages/core/package.json
- playground/monorepo_alt/packages/core/src/index.ts
- playground/monorepo_alt/packages/core/tsconfig.json
- playground/monorepo_alt/packages/kernel/package.json
- playground/monorepo_alt/packages/kernel/src/index.ts
- playground/monorepo_alt/packages/kernel/tsconfig.json
- playground/monorepo_alt/samples/project1/fuse.ts
- playground/monorepo_alt/samples/project1/src/index.html
- playground/monorepo_alt/samples/project1/src/index.ts
- playground/monorepo_alt/samples/project1/tsconfig.json
- playground/monorepo_alt/samples/project2/fuse.ts
- playground/monorepo_alt/samples/project2/src/index.html
- playground/monorepo_alt/samples/project2/src/index.ts
- playground/monorepo_alt/samples/project2/tsconfig.json
- src/tsconfig/__tests__/cases/case2/tsconfig-1-base.json
- src/tsconfig/__tests__/cases/case2/tsconfig-1.json
- src/tsconfig/__tests__/cases/case2/tsconfig-2-base.json
- src/tsconfig/__tests__/cases/case2/tsconfig-2.json
- src/tsconfig/__tests__/cases/case2/tsconfig-3-base.json
- src/tsconfig/__tests__/cases/case2/tsconfig-3.json
- src/tsconfig/__tests__/configParser.test.ts
- src/tsconfig/configParser.ts
Here we go again.
Added fixes, playground and tests.
Tests on configParser was successfull
@nchanged 
Please have new look at the new PR
>  fix: configParser - stop base config from overriding main

- src/resolver/__tests__/fileLookup.test.ts
...so it should indeed resolve that file :)
> fix: inverted unit test logic of resolver to not ignore local:main

- src/stylesheet/postcss/postcssHandler.ts
Added try/catch
If we had invalid css fusebox shut down an quit, se last S after `green;`
Error:
Added try/catch and logger message 😄 
Now it will not quit and user can fix error
> fix: add try/catch for postCss CssSyntaxErrors

- docs/plugins/pluginMinifyHtmlLiterals.md
- package-lock.json
- package.json
- playground/templateLiterals/fuse.ts
- playground/templateLiterals/package.json
- playground/templateLiterals/src/index.html
- playground/templateLiterals/src/index.ts
- src/index.ts
- src/plugins/core/plugin_minify_html_literals.ts
- src/production/stages/finalStage.ts
@nchanged @kyr0 
Have tried implement #1568.
Hopefully I havent messed up to much :joy:
> feat: pluginMinifyHtmlLiterals #1568

- docs/webIndex.md
- modules/web-index-default-template/template.html
- src/dev-server/devServer.ts
- src/interceptor/__tests__/interceptor.test.ts
- src/interceptor/events.ts
- src/web-index/__tests__/webIndex.test.ts
- src/web-index/webIndex.ts
Allows for async WebIndex plugins. Added documentation for `webIndex`. 
This PR relies on #1619 to be merged into master before.
> WebIndex: Async/await ICT support

- docs/plugins/pluginConsolidate.md
- src/index.ts
- src/plugins/core/plugin_consolidate.ts
This PR is based on PR #1619 and PR #1620 in this particular order :)
> pluginConsolidate

- src/plugins/core/plugin_replace.ts
> Plugin replace bug fix

- docs/getting-started/get-started.md
Added details, made things bulleted, removed certain things too detailed for noobies, tested the flow
> Re-organized "get-started"

- docs/development/transformerPlugin.md
Based on after merge comments in: https://github.com/fuse-box/fuse-box/pull/1707
> chore: Added doc about transformerAtPath

- src/resolver/nodeModuleLookup.ts
I found an edge case I'd not covered in my edit.
> Fix: local modules

- docs/getting-started/full-config.md
- docs/hmr.md
- docs/watcher.md
- modules/fuse-box-hot-reload/index.js
- src/config/PrivateConfig.ts
- src/config/extensions.ts
- src/core/Module.ts
- src/hmr/attach_hmr.ts
- src/watcher/watcher.ts
> feat(HMR): add hardReloadScripts option

- src/compiler/__tests__/__snapshots__/jsx.test.ts.snap
- src/compiler/__tests__/jsx.test.ts
- src/compiler/transformers/shared/JSXTransformer.ts
Fixing spread operator in JSXTransformer
Bug reported in slack channel, no issue
> fix: react transformer spread operator order

- src/resolver/__tests__/nodeModuleLookup.test.ts
- src/resolver/nodeModuleLookup.ts
(as discussed on Slack)
Module resolve in fuse-box does not match node's module resolution.  (This is one of the key issues with #1793 which mentions workspaces.  Workspaces and Lerna rely on node's module resolution).
For example, if you were to require `ImportMe` from the file `/home/alovelace/fuseapp/file.js` then node would search the following paths:
1. `/home/alovelace/fuseapp/node_modules/ImportMe`
2. `/home/alovelace/node_modules/ImportMe`
3. `/home/node_modules/ImportMe`
4. `/node_modules/ImportMe`
But fusebox will currently not search above its own root.  So it only searches the first path.  This can be worked around somewhat by changing the root, but this impacts other things and has its own cons.
This PR modifies the test case to match node's behavior and patches the behavior …
> fix: use node module resolution

- src/moduleResolver/asyncModuleResolver.ts
> fix: allow empty module content

- src/plugins/core/plugin_minify_html_literals.ts
fixed the pluginMinifyHtmlLiterals
> fix: pluginMinifyHtmlLiterals

- package-lock.json
- package.json
- src/env.ts
- src/plugins/core/plugin_consolidate.ts
- src/plugins/core/plugin_less.ts
- src/plugins/core/plugin_minify_html_literals.ts
- src/plugins/core/plugin_sass.ts
- src/plugins/core/plugin_stylus.ts
- src/plugins/core/shared.ts
OK, i had to nuke last PR because i rebased against master and didn't wanna figure out how to undo.
> Package manager suggestions (sorry lol)

- src/cache/cache.ts
Non-user packages like `semantic-ui-less` which contain modules which depend on modules in user-packages do not properly break cache when the user modules change.
Fuse-box appears to already be set up to handle this, but the feature is a little bit broken.  Fuse-box is already storing this relationship in `ctx.linkedReferences[]` and then when awakened by the watcher, if it checks the user modules and if they have been modified, it invalidates any modules that depend on them.  But when processing non-user modules, it never checks to see if these have been invalidated, so they never break cache.  This PR fixes that.
Note: there's another bug which is that when one of these linked resources would change, fuse-box was never resetting its modification time, so every time the watcher woke up …
> fix: make modifications of dependent files break cache for external modules

- src/sparky/sparky.ts
- Added RegExp support for task names
Relates to Issue: https://github.com/fuse-box/fuse-box/issues/1949
> feat(sparky): Add regexp support for task names

- src/compilerOptions/typescriptReferences.ts
Changes code to detect circular references along a given branch instead of looking for other references to the same project in the entire tree.
Fixes #1954
> fix: circular reference detection along branch

- src/sparky/sparky_chain.ts
> fix sparky src.dest chain #1986 and #1985

- src/webIndex/webIndex.ts
this make pluginConsolidate works(like ejs)
> fix: before_webindex_write applied for consolidate

- src/compiler/__tests__/__snapshots__/scopes.test.ts.snap
- src/compiler/__tests__/scopes.test.ts
- src/compiler/core/nodeSchema.ts
- src/compiler/core/nodeVisitor.ts
- src/compiler/core/scopeTracker.ts
- src/compiler/core/sharedContext.ts
- src/compiler/interfaces/AST.ts
declaration with var keyword has function scope. additional process needed
> fix: var scope calculation

- src/bundleRuntime/bundleSource.ts
- src/plugins/core/plugin_reactrefresh.ts
- website/versioned_docs/version-4.0.0/plugins/pluginReactRefresh.md
plugin for react refresh. 
it can be used like below(with path regex)
plugins: [
pluginReactRefresh(/(\/page\/|\/component\/|\/component-no-store\/)/),
]
> feat: plugin reactrefresh

- src/bundleRuntime/bundleSource.ts
- src/cache/cache.ts
- src/core/build.ts
- src/moduleResolver/bundleContext.ts
when no cache, module id changed on rebuild.
so i added another cache for module id cacheing.
> fix: when no cache, module id changed on rebuild

- src/watcher/watcher.ts
> fix: watcher root paths weren't being properly configured

- src/compiler/core/scopeTracker.ts
> fix: remove console log

- modules/ts_config_helpers/tslib.js
This fixed an issue with missing spreadarray helper
> fix: bring tslib forward to include new helpers
