fuse-box/fuse-box

test/node_exports.js
Fixed failing test: http.createClient was deprecated earlier and now removed in Node 7
=> http.createRequest was removed in Node 7

src/PathMaster.ts
Tsx compilation seems to work after I added .tsx to the allowed extensions list.
=> Added .tsx to allowed extensions

README.md, _playground/_build/index.html, _playground/bundle.js, _playground/ts/index.ts, _playground/ts/less/styles.less, _playground/ts/less/vars.less, dist/typings/WorkflowContext.d.ts, package.json, src-frontend/tsconfig.json, src/BundleSource.ts, src/File.ts, src/FuseBox.ts, src/PathMaster.ts, src/WorkflowContext.ts, src/index.ts, src/plugins/BabelPlugin.ts, src/plugins/CSSplugin.ts, src/plugins/ChainPlugin.ts, src/plugins/HTMLplugin.ts, src/plugins/JSONplugin.ts, src/plugins/LESSPlugin.ts, src/plugins/PostCSSPlugin.ts, src/plugins/SVGPlugin.ts, src/tsconfig.json, test/fixtures/cases/ts/tsconfig.json
***NOTE: I have added `less` as a dependency as it the only dependency for that plugin, unlike PostCss. Asking the user to import it and pass it in is overkill and makes the config bloated for no reason. I have an idea of how we can structure the plugins directory to make for a nice publish process and also make them self-contained***
- New `ChainPlugin`
- Moved `allowedExtensions` into top level config (because it wasn't needed due to plugins having a `test` and also so we don't need to pass an `extension` into the `ChainPlugin`
- Makes `WorkflowContext.init()` optional when implementing a plugin. It is not needed to set the extension anymore (see above). It can still be implemented if the developer needs/wants it.
- `File.loadContents()` now caches the content if it has been set, this …
=> ChainPlugin Implementation

_playground/_build/index.html, _playground/bundle.js, _playground/ts/index.ts, _playground/ts/less/styles.less, _playground/ts/less/styles.raw.less, package.json, src/plugins/CSSplugin.ts
- Use peer dependencies so users get prompted to install whichever version they like for plugin usages.
- Adds `raw` option to CSSPlugin, useful for Angular2 devs that wish to do:
```js
@Component({
selector: 'foo',
template: '<div class="foo">Foo</div>',
styles: require('./component.less/css/sass/etc.')
})
class Foo { }
```
=> Peer dependencies & extended CSSPlugin

_playground/bundle.js, dist/typings/WorkflowContext.d.ts, src/BundleSource.ts, src/FuseBox.ts, src/index.ts, src/plugins/BannerPlugin.ts
Requested from issue #31 
- Adds `preBundle()` and `postBundle()` plugin hooks
- Adds very basic `BannerPlugin`
I'm not sure if `postBundle()`is very useful. Originally my hope was to maybe use this hook for minification of the entire bundle, but I don't think thats possible. Happy to remove if it adds no value - let me know.
=> Proposal: Pre/PostBundle() Plugin Lifecycle Hooks

src/BundleSource.ts, src/ModuleCollection.ts
`WorkFlowContext` file name is `WorkflowContext` but imported as `import { WorkFlowContext } from "./WorkFlowContext";
`
=> change import path to match the file name.

src/ModuleCollection.ts
Attribute `pm` does not exist always and building crashes because it is missing when chaining several node modules. Here is a patch that passes the tests.
=> Verify that PathMaster exists before trying to use it

src/plugins/SassPlugin.ts
Related to #57 
Abandoned a check whether `options.includePaths` is an `Array` before pushing to it as `node-sass` docs require the user to pass an array.
=> Fix relative paths resolution by SassPlugin

src/plugins/PostCSSPlugin.ts
So I was using the PostCSS plugin and found that the CSS plugin was not receiving any contents - the Promise from the `transform()` was not resolving and just timing out. Turns out there was just a small fix: the promise being returned by the PostCSS's `transform()` was never resolving :) fortunately I just had to unwrap the inner call to `postcss.process()` and return that Promise.
=> should fix PostCSS plugin from not resolving the transform/task

src/FileAnalysis.ts
Class properties do not have a callee, but they are handled (apparently) as CallExpression. E.g. this would fail with `stage-2` babel preset
```
class Foo extends React.Component {
state = {
foo: 'bar'
}
}
```
Patched by checking explicitly that callee exists in the preflight check of the node
=> Class properties (e.g. stage-2) do not have a callee

assets/libs/fusebox-websocket/index.js
window.location.origin is used instead of window.location.host. This way protocol is included and matching will be done correctly and hot reload will also work over ssl connections.
=> Fix issue not able to use hot reload over ssl

assets/libs/tty/index.js
debug.js is a package used by many libraries out there and it depends on tty library. Following is a stub implementation of the only tty call needed by debug.js.
=> Extended tty definition to support for debug.js

docs/changelog.md
Minor spelling fix in changelog: `transpling` -> `transpiling`
=> Change log: Fix spelling in description of 1.3.108

src/PathMaster.ts
Npm packages [can have a browser-field](https://github.com/defunctzombie/package-browser-field-spec) if it supports both node and browser, Fuse-box should use the this fields.
=> Check if imported package has a browser-field and use it

src/Log.ts, src/PrettyError.ts
To fix #173.
Grey colors do not show up on solarized dark (and a few others). But the neutral color is already grey.
Here is solarized dark before the change (with some highlighing to show the invisible text)
Here is solarized dark after the change
For extra comparison here is Solarized light before and after
I tested several other themes just to be sure, but since this uses `reset()` it should be safe everywhere.
=> change brightBlack to reset get neutral color on dark themes

docs/builtin-plugins.md
Note the impotance of plugin order for `EnvPlugin`, explain `JSONPlugin`, explain default behavior of `UglifyPlugin`
(Sorry about the trialing whitespace removal, my editor did that automatically.)
=> add notes to env, uglify, and json plugins

src/FuseBox.ts, src/Log.ts, src/plugins/UglifyJSPlugin.ts
This is for #167, but it is not ready. I want to start a discussion.
This is what the report looks like currently
Obviously the lack of a label on the second report is one issue. I'm a little confused on how @nchanged wants to organize things. Things seem sort of abstracted around the `context` object, but the `Log` modules on `context` seems pretty specific to logging `ModuleCollection`, and their isn't another logging module. 
* Do you want a new logging module to abstract logging?
* Do you want `cursor` use directly in the `UglifyJSPluginClass`
* ... something else?
=> Report the new size and time taken for UglifyJS

src/File.ts
When transpiling files as modules, the filename is passed to TypeScript so it can interpret it properly. This is necessary to respect the behavior of the command line, especially when deciding whether files should be interpreted as jsx/tsx files, as per [the transpiler reference](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#transpiling-a-single-file).
See issue #213 for the original report.
=> Pass the source file name to the transpiler

docs/loader-api.md
closes https://github.com/fuse-box/fuse-box/issues/202
Key reasons why these docs are better: 
* Doesn't force the user to read the rest of the Loader API docs
* Provides a common use case of just reloading the window without any knowledge of how you have your code organized 
* Still shows all that there is to show about Loader Plugins :rose:
=> :memo: simply the docs for how to add a loader plugin :rose:

docs/loader-api.md, src/modules/fuse-hmr/index.ts
* Docs to disable HMR (requested here https://github.com/fuse-box/fuse-box/issues/207)
* Rename `check` to `isStateful` as it conveys the meaning if its return value better :rose:
=> Cleanups / docs

src/modules/fuse-hmr/index.ts
As requested https://github.com/fuse-box/fuse-box/issues/207#issuecomment-281185590 :rose:
=> remove return as `void` is not compatible with `boolean`

src/File.ts
If `homeDir` is set, it was not possibile to test node_module folder.
We should use app-root-path instead.
=> Allows testing plugin RegEx even if the `homeDir` setting is set

src/File.ts
I couldn't think of a regex that covers both JS & JSX, and supports correctly adding the x or not. 
Fixes #280
=> [TSX] Allow TSX files to be renamed back to TSX inside source maps

src/plugins/SassPlugin.ts
Fixes https://github.com/fuse-box/fuse-box/issues/278
=> Fixes user-defined sass includePaths from being overwritten

src/PathMaster.ts
=> Fixed checking if a module is a node_module on Windows

docs/builtin-plugins.md, docs/bundle.md, docs/configuration.md, docs/devserver.md, docs/format.md, docs/internal-process.md, docs/introduction.md, docs/plugin-api.md, docs/third-party-plugins.md, docs/tips.md, docs/typescript.md, gulpfile.js, package.json
docs:
+ add missing types to plugin api
+ expand upon some of the fns in plugin api
+ expanding on  in babel plugin
+ extended html plugin example
+ add debug and logs docs
++ add full config
++ unify instance names in bundle
++ adding standards file for consistancy in doc
++ adding internal process doc
+ adding all examples to third party plugins doc
+ some minor grammar fixes
iteration ability:
+ add gulp command to gulpfile and package json to install devdep
+ add missing nodetypes for tsconfig to resolve not-real errors in linting
=> docs, easier deps

docs/configuration.md
fix typo from `bundle` to `build`
add import syntax comment, 
add destructuring comment
=> fix "bundle" typo, comments

src/plugins/TypeScriptHelpers.ts
`.tsx` files were being ignored by the `TypeScriptHelpers` plugin—this PR fixes this.
=> Changed TypeScriptHelpers plugin test to support ts and tsx

package.json
ignore modules as they are mostly built utils which are not meant to be linted
=> ignore modules from lint

docs/builtin-plugins.md, gulpfile.js, package.json, src/index.ts, src/plugins/Markdownplugin.ts, src/tests/MarkdownPlugin.test.ts
A proposal based on the HTMLPlugin, to :
* support markdown files
* transform markdown files to HTML files
All of this is using marked library https://github.com/chjj/marked
The default marked options are the same than : https://github.com/peerigon/markdown-loader
=> Markdown plugin

modules/fuse-typescript-helpers/__generator.js
`self(){ ... }` is throwing errors in IE 9, 10, and 11. This small tweak keeps it ES3 compatible.
=> little tweak for __generator.js for IE9/10/11

src/core/WorkflowContext.ts
Omitting the return type of fn causes compile errors in consuming projects that import fuse-box with noImplicitAny compiler option.
=> Fix declaration for noImplicitAny

src/plugins/stylesheet/LESSPlugin.ts
This patch fix `@import` resolving inside the less file, if main less file isn't in root directory.
=> LESSPlugin: change filename path from relative to absolute

package.json, src/core/ModuleCollection.ts, src/plugins/EnvPlugin.ts
The collectBundle function is expecting a `Promise<ModuleCollection>` return, but gets a `Promise<void>`.
And when running a server bundle, environment variables don't get injected since the process shim isn't loaded.  But for browsers, people might wanna do vendor bundles that already includes the shim.
=> Fixed build error and add process shim for server bundles

docs/_meta.json, docs/plugins/transpilers/VuePlugin.md
@nchanged Would be nice to have a repository behind fuse-box organization for a Vue example, just like the Angular2 and React ones, so we can add it as a link in the documentation.
=> Add VuePlugin documentation

src/sparky/SparkFlow.ts, src/sparky/Sparky.ts, src/sparky/SparkyFilePattern.ts
Created a new interface called `SparkyFilePatternOptions` which is like this:
```typescript
export interface SparkyFilePatternOptions {
base?: string; // Will be ignored when parsing absolute paths
}
```
Added the interface as optional params to src() and watch() methods, and is actually used in parse method inside SparkyFilePattern.ts.
Now something like this would work:
```js
Sparky.task('copyAssets', () => {
return Sparky.watch('./assets', { base: './src' })
.dest('./dist')
})
```
And should fix #493
=> Add options to watch() and src() with 'base' param

docs/plugins/transpilers/VuePlugin.md, docs/sparky.md, src/sparky/SparkFlow.ts
Updated Sparky docs to add `options.base` #494 
Updated VuePlugin docs to include the new required module `vue-template-es2015-compiler` #485
=> Update VuePlugin and Sparky docs

src/sparky/SparkyFile.ts, src/sparky/SparkyFilePattern.ts, src/tests/sparky/SparkyFilePattern.test.ts
Updated Sparky tests adding a test for `base` option.
Fixed an edge case in Windows in `SparkyFile.ts` constructor, it just needed to `path.normalize()` the root path. This made the test fail in Windows.
Also:
```js
let hp = this.filepath.split(root)[1]; // Removed this
let hp = path.relative(this.root, this.filepath); // And did this instead
```
Which does the intended use and is a safer way to work with paths.
=> Update Sparky tests and fix a test for Windows

docs/plugins/transpilers/VuePlugin.md, src/plugins/VuePlugin.ts
As discussed in #492, adds custom template engine to be used by defining the `lang` attribute on the `<template>`  tag.
Also updated the docs for VuePlugin.
=> Added .vue components template preprocessing

src/plugins/VuePlugin.ts
Right now, the published version in NPM (2.0 beta 15 atm) breaks when the Vue template doesn't use any templating engine.
This fixes that, adding the missing `resolve()` call
=> Fix VuePlugin

src/plugins/UglifyJSPlugin.ts
This fix enables the use of either uglify-js 2 or uglify-js 3
=> Fix compatibility with uglify-js 3

src/sparky/SparkFlow.ts
This error happened some times on windows when doing this:
```js
return Sparky.watch('./assets', { base: './src' })
.dest('./dist')
```
`'./assets'` is passed to chokidar, which will emit `addDir` and `add` events, both will be handled and added to the files to copy, and then, make the copy.
The problem is that both folder AND files are being copied at the same time, and there's a race condition where a folder copy will happen before the file finished it's copy process. Resulting on 'No such file or directory' or EPERM errors.
This line prevents the copy of folders ignoring the addDir and unlinkDir events from chokidar. Because if a file is copied, it will already create the needed folders.
=> Fix EPERM error on Windows

src/BundleSource.ts, src/plugins/VuePlugin.ts
https://github.com/fuse-box/fuse-box/issues/513
Sourcemap path should be relative to source-file path, not to root distribution path.
Note: The issue specifies the problem on the server-side, while it is problematic also on the client-side
=> SourceMap path relativity

src/plugins/VuePlugin.ts
Fixed a bug where pug templates would not compile when using `include`. The `filename` parameter is required, even if set to something random.
=> VuePlugin: relative includes requires filename option (pug)

src/FuseProcess.ts
Alternative to .completed(proc=> proc.start()) that runs the script in the node instance used by fuse (debugging if fuse is debugged)
```
.completed(proc=> {
proc.require().then(exps=> {
// exps is the main module' exports
});
});
```
There are several ways to express how to close the deprecated instance once the bundle has been re-transpiled, when it is started again, depending on the AEFL (Automatically Executed File on Load)
If the bundle has NO AEFL, a close function taking no argument can be given as argument of `require`
```
proc.require(function() {
console.log('unloaded');
});
```
If the bundle HAS an AEFL, the first of these choice that exists/is defined will be used :
A- Give a close function to the `require` call, who takes an argument containing the exports of the AEFL
``` …
```
=> proc.require()

docs/introduction.md
The syntax for adding a package with `yarn` and saving it to `devDependencies` is `yarn add <name> --dev`.
It's a bit tricky to catch, though, because `yarn add <name> --save-dev` still works, and doesn't throw any warnings, but then actually saves the package to `dependencies` 😺.
=> fix `yarn add` command

src/BundleSource.ts
When a `FuseBox` is initialised with `debug: true`, the loader is injected non-minified in order to follow what is happening in the core of FuseBox.
This can help coders (who use `debug: true` in fuse-box) to find out where they failed their configuration or find bugs.
Note: I personally use that
=> Unminified version of the API on debug

modules/fuse-box-loader-api/fusebox.js, src/loader/LoaderAPI.ts
Solving: https://github.com/fuse-box/fuse-box/issues/518
When a module is not found or badly loaded in the browser, if there were no server errors (status: 200), FuseBox will use the response (and fail to register the module badly given) then import the module again ... as the module was not properly registered, the import will lead to an ajax request, and this will repeat indefinitely.
The correction brought here is simple (the infinite recursion is short) : The import will pass the option `ajaxed` to specify the file that was required to lead to that import. The function `$async` will, before creating an XHR object, check if by chance the request is not the one just done - and if yes, signal an error instead of repeating it.
=> Fix infinite requests caused by server's 200OK

src/plugins/WebIndexPlugin.ts
This one could save some hassle when working in react (namely, the notorious `Uncaught Error: _registerComponent(...): Target container is not a DOM element` error.
=> adding async tag to the injected scripts

src/core/PathMaster.ts
Currently the code checks for isBrowserTarget for the overrides variant of the browser field in package.json, but does not check it for the main variant of the field.
This PR hoists the target check to the entire browser field handling.
=> Don't use package browser field for non-browser targets

docs/plugins/transpilers/BabelPlugin.md, src/plugins/js-transpilers/BabelPlugin.ts, src/tests/plugins/BabelPlugin.test.ts
This PR enables extensions other than `".jsx"` to be registered with `WorkFlowContext::allowExtension(ext)`, thereby allowing use of custom extensions. 
I use the '.jsy' custom extension for [offside indented JavaScript dialect](https://github.com/shanewholloway/babel-plugin-offside-js). Think CoffeeScript, Python, or [Wisp](http://dustycloud.org/blog/wisp-lisp-alternative/). Being able to use the custom extension makes happy syntax highlighters much easier…
=> Adding support for alternative file extensions with BabelPlugin

src/analysis/plugins/ImportDeclaration.ts, src/core/PathMaster.ts
These changes enable browser target even when main entry point is not included in the browser overrides,
fixes also issue, when require statement is without file extension like in uuid `var rng = require('./lib/rng');` and package.json browser is with file extensions `  "browser": {
"./lib/rng.js": "./lib/rng-browser.js"
},`
=> fixes #610 with uuid style browser overrides

src/core/FuseBox.ts, src/quantum/plugin/ComputerStatementRule.ts, src/quantum/plugin/QuantumCore.ts
Omitting the return type of fn causes compile errors in consuming projects that import fuse-box with noImplicitAny compiler option.
```log
node_modules/fuse-box/dist/typings/core/FuseBox.d.ts(63,9): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/ComputerStatementRule.d.ts(8,13): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/ComputerStatementRule.d.ts(14,13): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/fuse-box/dist/typings/quantum/plugin/QuantumCore.d.ts(30,13): error TS7020: Call signature, which lacks …
```
=> Fix declarations for noImplicitAny

src/analysis/FileAnalysis.ts, src/core/File.ts
for when a plugin needs to manipulate or traverse the AST
=> feat: allow traversal plugins to be passed through makeAnalysis

src/plugins/WebIndexPlugin.ts
Add optional config props for common html metas.
```
WebIndexPlugin({
charset: 'utf-8',
title: 'Document Title',
description: 'A description of the web app',
keywords: 'keywords, that, represent, your, app',
author: 'Guy <guy@author.com>'
})
```
I also slightly modified the $title template variable to wrap the `<title>` tag for you, instead of having to include it in the template yourself.
I also fixed a bug in the default html template where the `$bundles` var is outside of the `<body>` tag.
=> Add charset/description/keywords/author metas to WebIndexPlugin config

docs/bundle.md
Since plugins actually append I updated the example to show that, and also
included an example where the option gets completely overwritten.
(It looks like I accidentally also deleted a bunch of trailing whitespace. If that is a problem I can fix it).
=> Update bundle plugin docs to match implementation. Fix #666

src/lib/postcss/PostCSSResourcePlugin.ts
CSSResourcePlugin was putting double parenthesis in url reconstruction
=> fix css url reconstruction

src/plugins/images/ImageBase64Plugin.ts
When using `ImageBase64Plugin({ useDefault: true })`, all the images can be references with the default import, but SVG couldn't.
=> SVG can be exported as default when using ImageBase64Plugin.

src/sparky/SparkFlow.ts
Hi all,
I'm using FuseBox as a dependency in my typescript project, and so I import FuseBox modules.
When compiling, TypeScript on Linux is throwing an error because of the case of a dependency :
```
import { Plugin } from '../core/WorkFlowContext';
```
in `src/sparky/SparkFlow.ts` should be
```
import { Plugin } from '../core/WorkflowContext';
```
=> Fix Sparkflow dependency

src/plugins/VuePlugin.ts
[Issue](https://github.com/fuse-box/fuse-box/issues/701)
Hi, here a little report for a specific VuePlugin usage.
When VuePlugin does not return a Vue options parameter but an instanciated Vue object, the render functions are not added to the options but to the instance - this leads to this error : [Vue warn]: Failed to mount component: template or render function not defined.
This happens on this line :
_p = Object.assign(_e.default, _p);
There, if e.default instanceof VueComponent (indeed, if typeof e.default === 'function' or even if !!e.default.options) then _e.default.options should be extended instead - it is really about adding a condition and a line.
Note: this use-case appears when vue-class-component or similar libraries are used, to have a completely typescript Vue definition.
=> Typescript under Vue

docs/plugins/css/LessPlugin.md
In Webpack one would use
```css
@import "~foo/dist/example.less";
```
See https://github.com/webpack-contrib/less-loader#imports
We should encourage users to provide node_modules path to plugin to avoid confusion around import statements.
Better, would be to adjust LESSPlugin to resolve paths prefixed by ~.
=> Suggest node_modules as path to pass to Less

src/quantum/plugin/QuantumOptions.ts
By checking specifically for `true` here, it prevents an uglify options object from being passed through Quantum.  
https://github.com/fuse-box/fuse-box/blob/master/src/quantum/plugin/BundleWriter.ts#L16 is already set up to take uglify options from this method.
=> allow uglify options via quantum

src/modules/fuse-hmr/index.ts
Following on from #710 - updates emitted as type 'css' were passed to the default HMR behaviour, which reloaded the entire graph of modules.
=> Fix CSS updates not being handled by fuse-hmr.

src/plugins/VuePlugin.ts, src/tests/plugins/VuePlugin.test.ts
Little change, big effects.
When a vue single-file component is defined, it exports the component as default :
```
@Component
export default class myComponent extends Vue {
```
So, it would seem logical to import it as default too :
```
import myComponent from '../components/myComponent.vue'
```
Instead, for now, the default has become the "whole" export, so we have to use this instead :
```
import * as myComponent from '../components/myComponent.vue'
```
Allowing it to remain `default`, beside notation consistency, would also allow component single-files to export other values, like global configurations, etc.
=> import as exported

docs/quantum.md, src/quantum/plugin/FlatFileGenerator.ts, src/quantum/plugin/QuantumOptions.ts, src/quantum/plugin/modifications/StatementModifaction.ts
When working with modules that are independently used server-side and client-side, there is a need of creating a module file that uses the standard require/module.exports, regardless of its usage on the server or in the browser.
I corrected here 2 little points about the "universal" target that, I think, was done for this figure case :
- The values exported by the fused module are given in module.exports (like in the case of "server" target)
- The unresolved imports are just imported with the `require` keyword.
This way, I could make a module that just exports functions, whether it is bundled for server or browser use.
=> Quantum "npm" target

src/plugins/VuePlugin.ts
https://github.com/fuse-box/fuse-box/issues/734
So again - as I need it I begun it.
Here is the first shot for Vue styling.
The CSS are loaded like other CSS files with `fuse-box-css` when the Vue file is loaded.
For now, only the un-scoped CSS is implemented (scoped and transpiled are not) so that we have time to chat about how & details.
One detail to know about transpilation is that I found only one generic transpiler for CSS : [accord](https://github.com/jescalan/accord)
It does quite the same job as `consolidate` except that consolidate doesn't deal with CSS pre-processors.
If you know of another, please say. If I use `accord`, perhaps it will be nice to replace what has been done with `consolidate`  afterward (I let you see)
=> Vue styling

docs/faq.md
Minor change, importing _ from "lodash", not lodash from "_"
=> Fix typo in faq.md

src/core/Bundle.ts, src/modules/fusebox-hot-reload/index.ts
* Send bundle errors to new browsers as soon as they open.  Previously they would only get the errors in the browser after a consecutive bundle execution.
* Allow user to minimize the error output in the browser
* This is persisted in local storage, so output stays minimized after refresh
* Minimized:
* Expanded:
* Allow user to hide the error output
* This is not persisted in local storage.  If a user doesn't want errors in the browser, they can set `showErrorsInBrowser: false`
Big thanks to @adye for putting together the styles 🎉
=> feat(error-logging): minimize/hide in browser

src/core/File.ts
Change to keep all the sources in sourcemaps for stylesheets and allow to see all related source-files in browser.
**current:** 
Source/Linking is only available for the main/root scss file in browser and all @imports are ignored
**should**
Provide sources/linking to all related files
**done**
As far I understood is `stdin` the current file if `data` is used as source [info](https://github.com/sass/node-sass/issues/591).
I'm not really sure if its working like expected with `fname`. This should't break anything but I think it will not work for all sources (vendor specific) because `fname` is not used for all of them. `fname` is provided [here](https://github.com/fuse-box/fuse-box/blob/882b7d6949e086386194d39b33b4ad65c56646d5/src/core/File.ts#L530) and used in `loadVendorSourceMap()`
=> Prevent overwriting of sources in sourcemaps (sass)

package.json, src/tests/CSSDependencyExtractor.test.ts
This sets the raw `package.json` data onto a `packageJson` property in `IPackageInformation`
Also gets the sass dep extraction tests working on windows.
The test for the `packageJson` property is a bit hacky, mostly because there is no way (afaik) to configure a PathMaster instance outside of the global Config object
=> feat: expose `package.json` in file info

docs/plugins/css/PostCSSPlugin.md, src/plugins/stylesheet/PostCSSPlugin.ts, src/tests/plugins/PostcssPlugin.test.ts
Should fix #788.
Sorry if I highjacked @ben33's pull request but we really need this to migrate to the new fuse-box version.
Please @ben33, tell me if it also solves your problem! Your review is very welcome.
In this PR, I migrated the old postcss tests.
I also added a new one, highlighting the issue mentioned in #788.
Some plugins, like the [url-plugin](https://github.com/postcss/postcss-url), need the postcss options to be passed through to work correctly.
---
@nchanged, I also think fusebox should follow some of [the guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/runner.md) provided by the postcss team.
Especially for the warning and the error processing.
I was thinking about adding a `.catch()` function to handle this in the plugin code, a bit like the less …
=> Postcss fix: pass options through to plugins

src/core/File.ts, src/core/ModuleCollection.ts
If I have a plugin that transpiles code/styles asynchronously then the updated `file.analysis.dependencies` are never processed by FuseBox.  
This is because the async `tryPlugin()` methods values was not used (i.e. didnt wait for promise resolution). So the processing had completed before FuseBox knew about the new dependencies.
Make FuseBox consume and wait for those promises to resolve before moving on, ensuring the new dependencies are resolved.
This could have a small impact on performance, but the project I am working on hasn't experience much change in execution time. Some minor TSLint errors have also been fixed.
=> Fix: Child Dependencies Not Resolved/Processed When Detected In Plugin.transform()

modules/fuse-box-responsive-api/index.js
Finalising the `globalRequire` idea :
The flag really solves a lot of issues. The only thing here is that it was not taken into consideration in the `npm` or `server` target case.
With this PR, it affects all the cases of `global.require` references.
=> globalRequire in case of npm (server)

docs/_meta.json, docs/plugins/html/ConsolidatePlugin.md, docs/plugins/transpilers/VueComponentPlugin.md, gulpfile.js, src/core/File.ts, src/index.ts, src/plugins/ConsolidatePlugin.ts, src/plugins/vue/VueBlockFile.ts, src/plugins/vue/VuePlugin.ts, src/tests/plugins/ConsolidatePlugin.test.ts
This adds the [consolidate](https://www.npmjs.com/package/consolidate) library as a plugin - which saves us creating *X* number of template renderers! Additionally, we utilise this new plugin in `VueComponentPlugin` so users can use any template language they see fit using either the `lang` attribute or inferring the `lang` from the `src` if specified.
=> Consolidate Plugin

src/core/FuseBox.ts
The old type was `Plugin[] | [Plugin[]]` ((array of Plugin) **or** (array of array of Plugin)) 
while I suggest `Array<Plugin | Plugin[]>`  (array of (Plugin **or** array of Plugin)). 
Only the latest is compatible with `fuse-box-examples` which have, on many occasions, an array of CSS-related plugins mixed up with single plugins.
=> Fix plugins field type from FuseBoxOptions

src/plugins/vue/VueScriptFile.ts, src/plugins/vue/VueStyleFile.ts
Moved TypeScript and PostCSS imports out of module scope as it was causing issues for people not using these modules in their projects.
=> VueComponentPlugin - Dependency Fixes

src/plugins/vue/VuePlugin.ts
When using [vue-class-component](https://github.com/vuejs/vue-class-component), the exported value is not the options but a `VueComponent` object that specifies options.
When this happens, the render option shouldn't be added to the default exported object but to its options
=> Allow class components

src/CacheBreaker.ts
I'm trying to run FuseBox in places like AWS Lambda, Firebase Cloud Functions etc. but they all fail because they have read only file systems and its this check that is causing it.
You might be wondering why I am doing this? Its for a cool new tool for the FuseBox community but its nowhere near ready to share...
=> Cache Buster - Handle "Non-Standard" Runtime Environments

src/plugins/vue/VuePlugin.ts
This resolves issue #852. I've also made sure that the `vue-hot-reload-api` is added as a dependency (if using cache).
=> fix: Only inject HMR code at end of bundle if a vue file has been processed

src/plugins/vue/VueBlockFile.ts, src/tests/plugins/VueComponentPlugin.test.ts
When using `<script lang="ts">` and the files default extension is `.js` the `VueComponentPlugin` would complain it could not find a matching plugin (when it should pick up Typescript). This PR fixes that.
=> fix: Ensures typescript plugin is used when vue lang="ts"

bin.js, package.json, src/analysis/FileAnalysis.ts
Updates acorn and removes invalidated plugins.
I'm not able to update `bin.js` which will cause the tests to fail. (manually updating it passes the tests)
=> chore: remove unnecessary acorn plugins

src/analysis/FileAnalysis.ts, src/analysis/acorn-ext/obj-rest-spread.ts
Found a fixed up fork/copy of the rest/spread operator in `@std/esm`
https://github.com/ternjs/acorn/issues/388
=> feat: object-rest-spread acorn parser extension

docs/plugins/transpilers/VueComponentPlugin.md, gulpfile.js, src/plugins/vue/VuePlugin.ts, src/tests/plugins/VueComponentPlugin.test.ts
This allows vue components to work with decorators such as `vue-class-component`:
```js
import Vue from 'vue';
import Component from 'vue-class-component';
@Component({})
export default class VueClassComponent extends Vue {
message: string = 'Hello!'
onClick (): void {
window.alert(this.message)
}
}
```
All the user needs to do is install `tslib` and update their `tsconfig.json` to `importHelpers`:
```json
{
"compilerOptions": {
"importHelpers": true
}
}
```
This also fixes a couple of other bugs:
- Hot reloading did not work for non-scoped styled components
- `DEFAULT_OPTIONS` were being extended each time a `VueComponentPlugin` instance was created.
=> feat: Allow typescript decorators for vue components

src/plugins/vue/VuePlugin.ts
The issue was being caused by a mismatch of the `fuseBoxPath` stored in cache and the `lastChangedFile` when using typescript as the .ts extension gets normalised to .js
This will fix #879
=> fix: Ensure correct path names for last changed file in bundle for VueComponentPlugin

docs/plugins/html/WebIndexPlugin.md, src/plugins/WebIndexPlugin.ts
As requested by @pyros2097 in #885 . Its a simple enough change so I did it real quick. Allows you to do the following:
```js
plugins: [
WebIndexPlugin({
templateString: `Your stuff here`
})
]
```
***NOTE:*** If you specify a `templateString` and `template` then `template` will take precedent
=> feat: WebIndexPlugin now accepts a template as a string literal

docs/bundle.md, docs/configuration.md, src/core/Bundle.ts, src/core/ExtensionOverrides.ts, src/core/File.ts, src/core/FuseBox.ts, src/core/WorkflowContext.ts, src/plugins/stylesheet/CSSResourcePlugin.ts, src/plugins/stylesheet/SassPlugin.ts, src/plugins/vue/VueBlockFile.ts, src/plugins/vue/VuePlugin.ts, src/tests/BundleApi.test.ts, src/tests/ExtensionOverrides.test.ts, src/tests/plugins/BabelPlugin.test.ts, src/tests/plugins/CSSPlugin.test.ts, src/tests/plugins/CoffeePlugin.test.ts, src/tests/plugins/ConsolidatePlugin.test.ts, src/tests/plugins/HTMLPlugin.test.ts, src/tests/plugins/JSONPlugin.test.ts, src/tests/plugins/MarkdownPlugin.test.ts, src/tests/plugins/RawPlugin.test.ts, src/tests/plugins/SassPlugin.test.ts, src/tests/plugins/StylusPlugin.test.ts, src/tests/plugins/VueComponentPlugin.test.ts
FuseBox can now be configured to look for customised extensions ahead of standard ones. This is
useful for platform specific builds. For example:
```js
FuseBox.init({
extensionOverrides: ['.desktop.js']
});
```
With the above configuration FuseBox will favour loading contents from files with a `.desktop.js` extension over `.js` extension. If `.desktop.js` does not exist then normal resolution will occur. This a essentially a port of the Webpack functionality for [resolve extensions](https://webpack.js.org/configuration/resolve/#resolve-extensions).
In Summary:
- Added Functionality
- Added Unit Tests
- Added Documentation
=> feat: Allow extension overrides configuration

docs/quantum.md, src/Utils.ts, src/quantum/plugin/QuantumPlugin.ts
I asked at gitter for the best way to design an API for it, but got no reply.  So here is the simplest implementation possible, though it probably isn't very straightforward to use.
It picks up uglify's options from the `UglifyESPlugin` or could be triggered by quantum option `uglify: { es6: true }`
=> feat: Uglify-es support for quantum

src/analysis/plugins/LanguageLevel.ts
As discussed in issue #916, I added detection of `const` and arrow functions `(...) => ...` since they are probably the most commonly used ES2015 features.
For complete language support, it would probably be better to create and use a separated module dedicated to this (something like 'acorn-detect-ecmaversion'), I didn't find anything existing covering this.
=> fix: LanguageLevel doesn't detect es2015 "const", "let" and "arrow function"

docs/plugins/transpilers/BabelPlugin.md, gulpfile.js, src/plugins/js-transpilers/BabelPlugin.ts
Issue identified by @apostololeg in #919 
The fix here is to merge both the `.babelrc` and `BabelPlugin(options)` together. Previously the plugin would just use the `.babelrc` file if it existed and ignore any options provided directly.
=> fix: Ensure .babelrc options and direct BabelPlugin options are merged

src/lib/postcss/PostCSSResourcePlugin.ts
Currently `PostCSSResourcePlugin` targets background images and fonts when it looks for `url(...)` values.
This PR adds support for CSS `mask-image` property.
so this:
```css
-webkit-mask-image: url("mask.svg");
```
can be transformed to:
```css
-webkit-mask-image: url("/149583776.svg");
```
I would have written some tests, but I did not know how to setup the tests as there does not seem to be any existing tests for `CSSResourcePlugin` / `PostCSSResourcePlugin`.
=> feat: allow CSS mask images to be processed with PostCSSResourcePlugin

docs/plugins/html/WebIndexPlugin.md, src/plugins/WebIndexPlugin.ts
for cross-usage with other bundlers, it would be nice to have an option to automatically append `$bundles` to template.
=> feat: add `appendBundles`-option to WebIndex-plugin

src/Utils.ts, src/plugins/stylesheet/PostCSSPlugin.ts
PostCSS recommends (if using a PostCSS extension) to use .pcss
https://twitter.com/postcss/status/661645290622083073
IntelliJ
> The IDE now recognises .pcss files.
https://plugins.jetbrains.com/plugin/8578-postcss-support
=> feat: PostCSS added support for .pcss extension

src/sparky/SparkFlow.ts
#995
When using `Sparky.watch` with a parent base directory, (because my `fuse.js` file is in a subdirectory (see screenshot)) it wouldn't copy files to my `.dest` directory.
```js
Sparky.task("watch-assets", () => Sparky.watch("./assets/*.png", { base: '../src/' }).dest('../dist'));
```
Using the `ensureUserPath` fixes this. 
My folder structure would be:
And my full `fuse.js` file looks like this:
```js
const {
FuseBox,
WebIndexPlugin,
Sparky
} = require("../../../.dev");
let fuse;
const DIRS = {
src: '../src',
dist: '../dist',
assets: './assets'
}
Sparky.task("clean", () => Sparky.src(DIRS.dist).clean("dist/"));
Sparky.task("watch-assets", () => Sparky.watch(`${DIRS.assets}/*.*`, { base: DIRS.src }).dest(DIRS.dist));
Sparky.task("copy-assets", () => Sparky.src(`${DIRS.assets}/*.*`, { …
```
=> fix(sparky): Update watch flow to use user base path

src/lib/CSSDependencyExtractor.ts, src/plugins/stylesheet/CSSModules.ts, src/plugins/stylesheet/PostCSSPlugin.ts
The CSS Modules spec has a syntax for defining values which can be imported from within a css or js file. This syntax is supported by default via the postcss-modules library, so it works well for the first compile with fusebox. However, dependencies introduced by `@value` imports within CSS aren't tracked, so changes to the values themselves are not applied until the importing file is reloaded from some other change.
For example, 
main.css:
```css
@value primary from "./colors.css";
body {
background: primary
}
```
colors.css:
```
@value primary: red;
```
If colors.css is modified so that primary is green, main.css is not reloaded and the change is not applied. This PR fixes that behavior. I also noticed that the PostCSSPlugin mutates its `paths` param, which is fixed.
I'm not 100% sure …
=> Support HMR of files included through CSS Modules @value

docs/configuration.md, src/core/File.ts, src/core/FuseBox.ts
I've also set the default language level to ES2016 for compatibility with the old ES6 default which was actually ES7/ES2016. If the default should actually be ES6 then it may be best to use ES2015 form - avoiding the ESx aliases entirely within the codebase.
(It's so easy to get the ES year mixed up - i'm doing it myself now, you may notice from the extra commit!!!)
Added some notes to docs regarding aliases and recommendation to use year form, and state the default.
Personally i'd ditch the es-edition aliases entirely and go with the es-year form always, but i don't know if you need them for possible TypeScript configuration compatibility.
=> fix: ScriptTarget ES-edition to ES-year aliases (#990)

docs/plugins/css/LessPlugin.md, src/plugins/stylesheet/LESSPlugin.ts
This PR adds the `relativeUrls` option to `LESSPlugin`.  Its necessary when you want to automatically rebase urls in imported less files relative to the entry file.  The previous fix for filename is actually only ever used (AFAIK) when `relativeUrls` is turned on so I believe nothing should be broken by that.
=> Allow relative URLs in less files

modules/fuse-box-responsive-api/index.js
Missed this before as I wasn't yet making use of Quantum :)
=> fix: Fix #1030 (`this !== module.exports`) for Quantum

src/lib/CSSUrlParser.ts
When the `extractValue()` method returns undefined a TypeError occurs because an operation is applied on a variable that doesn't exist. If `extractValue()` returns undefined the `match` value should be returned which fixes the crash.
=> Fixes #1084

modules/fuse-box-responsive-api/dev-imports.js
It will with normal fn support IE11, which now throws Syntax error because of => function.
=> normal function expression instead of => function

src/lib/CSSUrlParser.ts
Not sure how it really supposed to work in such cases, but without this check it fails with 
```
TypeError: Cannot read property 'startsWith' of undefined
at walker (fuse-box\plugins\stylesheet\CSSResourcePlugin.js:104:21)
at contents.replace (fuse-box\lib\CSSUrlParser.js:24:30)
at String.replace (<anonymous>)
at Function.walk (fuse-box\lib\CSSUrlParser.js:22:25)
at CSSResourcePluginClass.transform (fuse-box\plugins\stylesheet\CSSResourcePlugin.js:160:53)
...
```
=> fix: data URLs handling in CSSResourcePlugin

src/core/File.ts
Outputs any errors that occur during transpilation and shows the file where they happened.
Did not test this, just edited the file here directly on github.
=> Catching typescript transpilation errors

modules/fuse-box-loader-api/fusebox.js, src/BundleSource.ts, src/core/WorkflowContext.ts, src/plugins/EnvPlugin.ts, src/plugins/vue/VuePlugin.ts
Hello, i have fix error on VueComponentPlugin and optimize plugins on electron.
Changes :
-  Fix error "Uncaught Package not found process" when use VueComponentPlugin in development.
This error is produced because VueComponentPlugin call `FuseBox.import("process")` before define `FuseBox.target`.
This fix, fix probably other bugs when we need falls functions before `FuseBox.target`, `FuseBox.isServer` and `FuseBox.sdep`.
For fix that i have just move this lines to start bundle.
- Add verry small memory save on FuseBox loader when check if is browser (variable : `$isBrowser`). This variable now store only boolean and not reference to `window.navigator`
- Optimize VueComponentPlugin when running on electron or server.
For this, i have replace `FuseBox.import('process')` by …
=> Fix error on VueComponentPlugin and optimize plugins on electron

src/plugins/vue/PostCSSPlugins.ts
Hello, the implementation for `postcss-selector-parser` on [PostCSSPlugin#50](https://github.com/fuse-box/fuse-box/blob/master/src/plugins/vue/PostCSSPlugins.ts#L50) is wrong.
I have fix the `undefined` selector with that.
=> Fix the scoped selector for vue

src/plugins/vue/VueStyleFile.ts
Hello, i have fix this error: `Without 'from' option PostCSS could generate wrong source map and will not find
Browserslist config. Set it to CSS file path or to `undefined` to prevent this w
arning.`
=> Fix postCSS error "without 'from' option"

src/analysis/plugins/LanguageLevel.ts
Code containing template literal now correctly idenfied as ES2015
=> feat(languagelevel): adds template literal as identifier of ES2015

package.json
Here's the error message
```
Error: Cannot find module 'source-map'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (...\node_modules\fuse-box\core\SourceMapGenerator.js:4:19)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
```
=> add source-map to package.json dependencies

package.json, src/core/TypescriptConfig.ts
I was having issues using the default `tsconfig.json` provided by `tsc --init`. This file includes comments which are not support by NodeJS's default JSON parser. I've switched to an alternative parser to support JSON comments.
=> fix: Support tsconfig.json with comments

package.json, src/core/TypescriptConfig.ts
Right now fuse-fox fails if tsconfig.json has trailing commas, which is valid, because of the use of the library comment-json that doesn't support it.
But theres no need to use a library because typescript api provides a method.
=> fix error when tsconfig.json has trailing commas

docs/plugins/html/WebIndexPlugin.md
The $css macro was missing in the doc.
=> Added the $css macro in custom template

src/Log.ts, src/core/FuseBox.ts
- sorted bundle sources for easyier checking, that package/file `whatever` is bundled
- fixed all autofixable tslint errors in affected files
before:
```log
Bundle "vendor"
└──  (0 files,  53 Bytes) default
└── fusebox-hot-reload 7.6 kB (1 files)
└── fusebox-websocket 2.9 kB (1 files)
└── events 9.8 kB (1 files)
└── react 50.1 kB (3 files)
└── object-assign 2.2 kB (1 files)
└── fbjs 17.6 kB (16 files)
└── process 4 kB (1 files)
```
after:
```log
Bundle "vendor"
└──  (0 files,  53 Bytes) default
└── events 9.8 kB (1 files)
└── fbjs 17.6 kB (16 files)
└── fusebox-hot-reload 7.6 kB (1 files)
└── fusebox-websocket 2.9 kB (1 files)
└── object-assign 2.2 kB (1 files)
└── process 4 kB (1 files)
└── react 50.1 kB (3 files)
```
=>  feat: sorted bundle sources

docs/development/configuration.md, package.json, src/Log.ts, src/core/FuseBox.ts, src/quantum/plugin/BundleWriter.ts
Adds some useful logging options.  Note that this is not backwards compatible, so anyone using `log: true` or `log: false` will need to change their config or will get a type error.
=> feat: log option now takes an object

src/plugins/WebIndexPlugin.ts
I have a scenario in which I am only loading JS if I am on a specific browser, supporting ES6 with async await. For all other browsers I am disabling the app. It is a corporate app so don't judge.
I can now do:
```html
<script type="text/javascript">
function isGeneratorSupported() {
try {
eval('(function*(){})()');
return true;
} catch (err) {
return false;
}
}
let c = document.getElementById('hiddenContent');
if (!isGeneratorSupported() || /MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
c.style.display = 'block';
} else {
$bundles
} 
</script>
```
and
```js
WebIndexPlugin({
template: 'src/client/index.html',
emitBundles: bundles =>
bundles
.map(b => `document.write('<script type="text/javascript" src="${b}"><\\/script>');`)
.join('\n')
}),
```
=> Possibility to shape how bundles are emited

src/quantum/plugin/QuantumSplit.ts
Requesting code-splitted js files at e.g. `http://localhost:4444/foo/bar/baz` didn't work but this PR should fix it.
=> Fix nested routes bug

README.md
Also, http://fuse-box.org/page/examples-and-seeds is broken with `TypeError: item.children is undefined`.
=> Specify the file name

src/plugins/stylesheet/CSSResourcePlugin.ts
https://developer.mozilla.org/en-US/docs/Web/CSS/filter
The url filtering on this plugin isn't very good, it's not taking into account all the possible combinations. Perhaps it's a good idea to consider reworking this.
For now, this will fix my project as I have something that looks like this:
filter: url(#blurMe);
Please merge and release!
=> CRITICAL: CSSResourcePlugin parse error

src/core/File.ts
fixes #1204, and also includes an import check for importing HTML files with the ng-template plugin.
=> Made error message clearer, and included HTML Template file not found error check.

src/core/Bundle.ts, src/core/FuseBox.ts
When an error is thrown in plugin, there are bugs making such error not properly propagated to the top level Fusebox.run.  This caused our CI pipeline failed to catch the plugin issue and shipped broken code.
This MR fixes the bugs.
=> Fix some error propagation bugs.

src/plugins/vue/VuePlugin.ts
https://github.com/fuse-box/fuse-box/issues/1194
Having two vue files in one folder is making conflicts - in the source map as well as in the style management.
By using the file' name, we have unique names.
Before:
folder/myVue.vue -> folder/script.ts
folder/foobar.vue -> folder/script.ts
After:
folder/myVue.vue -> folder/myVue.vue.ts
folder/foobar.vue -> folder/foobar.vue.ts
=> fix: renaming generated files to allow several vue files in a folder

docs/plugins/css/CSSModules.md
Added missing documentation for `root` option on `CSSModules`
=> docs: CSSModules root

gulpfile.js
Copy README.md to dist folder so npm doesn't look so empty :P
=> Copy readme so it's included in npm

docs/sparky/sparky.md
This fixes https://github.com/fuse-box/fuse-box/issues/1279
The `&` prefix means `parallel`, not `waterfall`.
=> docs: fix typo in sparky waterfall-parallel

src/plugins/stylesheet/CSSResourcePlugin.ts
This option allow developer to create a manifest of generated resources files. Needed when loading CSS Resources from Javascript.
This fork manages watch loops to allow filesMapping function to create typescript or javascript files in homeDir folder.
filesMapping can also create a JSON file loaded at runtime for example.
Usage :
```
CSSResourcePlugin({
dist: "resources/",
// Called when a new set of resources is copied to the resources/ folder
filesMapping: (files) =>
{
// Log copied files
files.map( fileMapping =>
{
console.log(fileMapping.from, "has been copied to", fileMapping.to)
});
}
})
```
=> Adding filesMapping option to CSSResourcePlugin

src/devServer/HTTPServer.ts
As the fallback route is defined before any proxies it's currently not possible to use both proxy and fallback.
=> fix: move devServer fallback after proxy

src/core/File.ts
Since commit [66f06bb3](https://github.com/fuse-box/fuse-box/commit/66f06bb358bc3673412fd4b37c19c29dbad83505#diff-cb5978b5d218f988ba81132ae01eb62fR454) wildcard imports are broken.
This PR fixes this issue:
I've added a check - if file path includes `*` then don't throw any errors.
=> Fix: Don't throw asset reference error on wildcard imports

package.json, src/cli/entry.ts
Hey @nchanged! Here is the PR to swap minimist for [getopts](https://github.com/jorgebucaran/getopts). Getopts is a lighter/faster alternative to minimist. They have the same API, so this is essentially a "drop-in" replacement. 
This is a non-breaking change. See full [benchmarks here](https://github.com/jorgebucaran/getopts/tree/master/bench) if you like.
<pre>
mri × 374,999 ops/sec
yargs × 32,370 ops/sec
<b>getopts × 1,495,165 ops/sec</b>
minimist × 283,031 ops/sec
</pre>
Let me know if this looks good to you. Cheers!
=> Swap minimist for getopts

package.json
Remove unused package `yargs`.
@nchanged I didn't update the [old docs still mentioning yargs](https://github.com/fuse-box/fuse-box/blob/master/docs/cli_api.md#options), as I am not sure what's the direction you'd want to take. 
**Possibly Related**: https://github.com/fuse-box/fuse-box/issues/1321
=> Remove unused yargs.

docs/development/configuration.md
I'm pretty sure there isn't a bundle.output - instead this should be bundle.context.output.
=> Minor documentation change: bundle.output replaced with bundle.context.output

src/quantum/core/nodes/RequireStatement.ts, src/quantum/tests/OptimisedBundle.test.ts, src/tests/stubs/test_modules/@bar.foo/animations/browser/index.js
This fix aims at supporting any [valid npm package name](https://docs.npmjs.com/files/package.json#name) under a namespace.
Fusebox is currently unable to recognize `@deck.gl/core` because of the `.` present in the namespace (and any packages under the `@deck.gl` namespace) as valid `node_modules`.
This in turn makes the build fail since required modules are not referenced in the final output `$fsx.r(<name>)` instead of a valid `$fsx.r(<ID>)`.
=> fix: match against valid npm namespace + package name

src/core/WorkflowContext.ts
fixes #1335
Nuking the queue together with the cache makes the watcher resume after an error in reproduction http://github.com/sod/fuse-box-watcher-issue
@nchanged
=> fix: watcher can't resume if queue contains a rejecting promise

src/core/FuseBox.ts
Tried to set `log.showBundledFiles = false`, but it had no effect. Had to look in the source code why. 
`doLog` is always just set back to default, so this PR changes to don't set it at all. And always apply `log.showBundlesFiles`, if found.
Fixes following configs:
```js
FuseBox.init({
log: {
showBundledFiles: false, // <- was ignored
},
});
FuseBox.init({
log: {
enabled: false, // <- was ignored
showBundledFiles: false, // <- was ignored
},
});
```
Those cases now work plus cases that already worked like:
```js
FuseBox.init({
log: {
enabled: true,
showBundledFiles: false,
},
});
FuseBox.init({
log: true,
});
FuseBox.init({
log: false,
});
FuseBox.init({
// defaults to true if not set
});
```
@nchanged
=> fix: log.showBundledFiles ignored when log.enabled value missing

package.json, test.js
- test.js script should be easier to understand
- test:once script is removed because it's not needed and there are no mocha tests
I hope I was right that `test:once` is no longer needed, please correct me if I'm wrong, I'll revert the change and add a documentation on what's the purpose of it.
=> refactor(test.js): Refine test runner and npm scripts

docs/development/watching.md, src/core/Bundle.ts, src/core/BundleProducer.ts, src/tests/BundleApi.test.ts
`filterFn?` is a function that filters which watch changes trigger a
re-bundle, as an alternative to the pseudo-glob syntax of the
previous `rule` parameter. This is motivated by the need to more
easily exclude files generated by my editor ('flycheck_*`).
=> feat: add optional `filterFn` parameter to `Bundle.watch()`

website/siteConfig.js
Server side configuration is available in Algolia's repository: https://github.com/algolia/docsearch-configs/blob/master/configs/fuse_box.json
@nchanged can you fix up styles for the "powered by" button?
=> docs(website): Add search powered by Algolia

src/plugins/stylesheet/CSSModules.ts
Possible fix for #997.
Not sure which test case I should update, didn't see any covering CSSModules plugin.
=> fix: use correct CSS file path

src/analysis/plugins/LanguageLevel.ts
First tried to just add the new if statement to identify usage of classes. But no transpilation was done even though my tsConfig target was ES5. Turned out the tsConfig target is ignored. The only thing that matters is explicit targets set in your fuse.js. If you don't set an explicit target, ES2016 is assumed, not your tsConfig target.
I've attempted to solve it by comparing against the tsConfig target instead of the context target. Don't know if it's the correct way to go about it.
=> fix: improved detection of language level for transpilation

modules/stream/index.js, package-lock.json, package.json
@nchanged - I've made the changes to the stream polyfill (domain is already fixed in #1438 ). I'm currently requiring in `stream-browserify` but let me know if you want this as inline code instead.
I haven't been able to run tests properly as I've ran into issues running `gulp dev` on my machine. Essentially it boils down to this: https://stackoverflow.com/questions/53146394/node-app-fails-to-run-on-mojave-referenceerror-internalbinding-is-not-defined
Ultimately, I would need to upgrade gulp to v4 (and get a new vinyl-fs and new natives).
Guessing this would have breaking changes so I've held off on this. But let me know if you want some PR effort on this.
=> fix: adds stream-browserify as stream polyfill for browser

modules/fuse-box-responsive-api/dev-imports.js
Using a ES6 feature in dev-imports.js breaks uglifyjs.
=> Make sure dev-imports.js es5 only.

docs/plugins/babel7.md, package.json, src/plugins/js-transpilers/Babel7Plugin.ts, src/tests/plugins/Babel7Plugin.test.ts, website/sidebars.json
Hello there,
I've ported babel plugin to use babel7 core module. The discussion can be found [here](https://github.com/fuse-box/fuse-box/issues/1364)
I've mentioned that I wanted to make babel auto polyfill work together with this plugin. However, to keep this simple, I've only ported the previous plugin to make it work with babel7.
Notes:
- `ast: true` is provided and merged explicitly with the config because on babel7 this property defaults to `false`. To sum up, to keep it consistent with the previous babel plugin.
- Technically there is no need for this plugin to handle loading `.babelrc` since `configFile` or `babelrc` props can be passed as part of the config [(see #configfile)](https://babeljs.io/docs/en/options#configfile) and let babel core handle it. However, this is up for …
=> Babel7Plugin implementation

src/sparky/SparkyContext.ts
The type of `target` should allow for a class, a function returning a plain object, or a plain object.
=> fix(Sparky): correct target type of SparkyContext (resolve #1464)

docs/plugins/babel7.md, src/plugins/js-transpilers/Babel7Plugin.ts, src/tests/plugins/Babel7Plugin.test.ts, src/tests/plugins/Babel7PluginConfig/plugin-test.js
Hey,
- solves the issue mentioned at [issues/1463](https://github.com/fuse-box/fuse-box/issues/1463) that happens when `filename` is not passed when transpiling in the configuration. Some plugins wouldn't work before
- improves defaults or required config that must be always set in order to transpile. e.g: `ast: true, code: true, ...`
- validates configuration with `loadOptions` and `loadPartialOptions` from Babel7 core which ensures a valid configuration is provided on init. e.g: presets and/or plugins are resolvable and fails when extra properties or typos in properties' names
- added handling babel JS config files such as `babel.config.js`
- improve lookup for `.babelrc` or `babel.config.js` files relatively to `homeDir`
- added option `fileConfig` which can be `false | string | …
=> Improve Babel7Plugin and handle JS Babel configuration

src/devServer/HTTPServer.ts
I have a use case where I'd like for the `Development Server Running...` log message to be disabled while other information populates the user's terminal, and I found it a bit surprising it wasn't disabled when FuseBox is created with `log: false`.
Additionally, thanks for working on such an awesome project 🌹. I greatly appreciate the strong TypeScript support as it aids me in my own TypeScript tooling projects. I plan to contribute more in the future as I can, so please let me know if there is anything I can do to improve this PR.
=> feat($devServer): Use fusebox logger for HTTPServer logging

src/plugins/js-transpilers/Babel7Plugin.ts, src/tests/plugins/Babel7Plugin.test.ts
Discussion: [issues/1364](https://github.com/fuse-box/fuse-box/issues/1364)
- resolve imports/requires injected by `@babel/preset-env` to `core-js` polyfills if `useBuiltIns` option is defined to `usage`. This option is still experimental in Babel7. However, if there is any other babel plugin that injects imports/requires, those will be resolved as well
- added test to check if polyfill resolved as expected
=> Babel7 resolve imports/requires injected by preset-env (polyfills)

src/Log.ts, src/Utils.ts, src/analysis/plugins/LanguageLevel.ts, src/core/CombinedTargetAndLanguageLevel.ts, src/core/File.ts, src/core/FuseBox.ts, src/core/TypescriptConfig.ts, src/index.ts, src/quantum/plugin/BundleWriter.ts, src/tests/CombinedTargetAndLanguageLevel.test.ts, src/tests/QuantumCSSplitting.test.ts
[issues/1457](https://github.com/fuse-box/fuse-box/issues/1457)
- ensure typescript is installed. Checks on `index.js` since it's the earliest when TS is not used
- ensures minimal version of TS is `3.0`. Okay? :P
- replace `ScriptTarget` enum with `ts.ScriptTarget`
- parse and validate `compilerOptions`
- only done once before cached
- format error|warning|message using TS formatter but displayed as standard FuseBox errors/warnings format
- once parsed, `compilerOptions` is compatible with `ts.CompilerOptions` which replaces strings with equivalent enums' values. For instance, `jsx: "react"` will be `jsx: ts.JsxEmit.React`. This is helpful for not having mixed configuration (string values | number values)
- explicitly unset/set `compilerOptions` used in `transpileModule` …
=> Report diagnostic errors on compilerOptions - #1457

src/core/CombinedTargetAndLanguageLevel.ts, src/core/FuseBox.ts, src/core/TypescriptConfig.ts, src/core/WorkflowContext.ts, src/tests/CombinedTargetAndLanguageLevel.test.ts, src/tests/TypescriptConfig.test.ts
- ensure language level is always numeric
- better cast from string|numeric language level to always -> numeric language level
- rename `tsConfigFileCompilerOptions` to `rawCompilerOptions` and improvement on types (e.g: removing `Latest` and `JSON` from `target` which is valid in enum but not as string in raw compiler options)
- refactor of `read`. Same logic/order but simplified the non-pretty if blocks :P
- add support for reading `jsconfig.json` file. Only difference is adding `allowJs: true` to config. Currently not used but may come in handy in plugin writing and it follows standard
- most important, add big test file for `TypescriptConfig`
- language level casting (number -> string, string -> number)
- test generated tsconfig. File content must be in `raw` compiler options while …
=> Improve tsconfig checking

docs/plugins/sass.md, src/plugins/stylesheet/SassPlugin.ts
dart sass (https://github.com/sass/dart-sass) is now stable and has a javascript version published that can be installed via `npm install sass`. Dart sass it the official implementation of sass and new features will be there first. The api is the same, so you can drop in either of both.
It has an optional dependency `fibers` that increases performance.
node-sass is stil faster. But as your fuse-box caching makes transpiling a rare occurance anyway, it would be nice if the SassPlugin could use both, `node-sass` and `sass`, depending on what the user installed.
@nchanged
=> feat: SassPlugin supports both, node-sass and sass (with fibers optional)

package-lock.json, package.json
This update addresses [jprichardson/node-fs-extra@ddc1a2f](https://github.com/jprichardson/node-fs-extra/commit/ddc1a2f9d42da77342d58f6fd86942a231f5f27f) which was introduced into fuse-box when fs-extra was updated in this PR https://github.com/fuse-box/fuse-box/pull/1341/files
=> chore: update fs-extra dependency

modules/fuse-box-responsive-api/index.js, modules/fuse-loader/index.js, modules/fuse-loader/index.ts
This should fix the issue with the Babel import polyfill (and any similar helper functions)
=> fix: Synthetic default export polyfill does not add __esModule property

src/core/writer.ts
Added missing 'await' to a returned promise in the async 'write' function.
Without this, sometimes tasks relying on the written file to exist are run before the file is ready; e.g., running the server bundle.
=> Wait for writes to finish before resolving

.vscode/launch.json
This makes it really easy to debug a playground.
Hopefully it will make it easier for someone liek me to help.
How to use:
* set breakpoint somewhere in fuse src you know you project will run
* open playground fuse.ts file, select
Debugger will now stop at you breakpoint
=> chore: start vscode in debugging mode from selected TS file

.vscode/launch.json
Removed old jest run. It was bad since it only ran 1 test.
With the new one you just select the jest test you want to run.
Also renamed the old debugging with ts-node
=> chore: improve debugger (jest) & rename old debugging mode

src/dev-server/devServer.ts, src/dev-server/hmrServer.ts, src/hmr/attach_hmr.ts
Quickfix for the HMR
This will stop HMR from calling each client multiple times with new content.
Also added simple cache for generated content so we dont regenerate each time
But think we should have maybe some defined events so we easly know how to use it.
Call all clients or just respond to caller.
Atm from what I can see we only have 3 events
- server -> get Summary to all clients 
- clients resond with summary
- the server calls back with new payload
Ive just tested with "monorepo_alt", might be stuff I dont know about that can break this.
=> fix: hmr, 1 payload per client and cache content

src/resolver/__tests__/shared.test.ts, src/resolver/shared.ts
Tried to fix the order.
ts_main should come before module/main but after local:main (alias/paths directories)
=> fix: give ts:main precedence over module in package.json

src/dev-server/devServer.ts
This fixes #1553 but also in general all types of errors that could occur while devServer startup
=> feat(PortInUse): Exit gracefully

docs/development/plugins.md, src/interceptor/__tests__/interceptor.test.ts, src/interceptor/interceptor.ts
This PR adds the functionality to async/await for callbacks registered with an interceptor. 
Based on this implementation, fuse-box can decide internally where it wants to wait for all registered callbacks to finish before it continues it's work.
The new API `awaitForSync` is backward compatible with all callbacks registered using `on` and `awaitOn`.
The old API `sync` can handle callbacks registered by `awaitOn` in theory, but it is likely that the fuse-box internal code will fail because it doesn't expect a Promise as a return value. You really have to use the API wrong to come into this situation. But when we add a list of events to the documentation, we should also document which ones shall be sync and async
=> Awaitable ICT

src/web-index/__tests__/webIndex.test.ts, src/web-index/webIndex.ts
Fixes issue #1618 -- but I took a bit different approach, open for discussion:
1) I didn't generate the index.html because we'd change the developers code by doing this. Thats always a dangerous thing to do for a build system, especially when we do that automatically -- instead I use a default template on the fly and warn that there is no index template file. So if the developer wants, the file can be created by him but if he doesn't, the project builds anyway. Perfect for zero-config setups and super simple setups.
2) I changed the default template to add some useful headers for modern devices like viewport and edge support, UTF-8 charset etc.
=> feat(WebIndexDefaultTpl): Default WebIndex template allows for zero-config setup

src/sparky/sparky_chain.ts, src/sparky/sparky_src.ts
@nchanged 
Think Ive found the root of my issue.
Need to test more and find a good way to add test to this. I only ran the sparky tests. 
Problem is when its started from package root with something like npm or directly `node ./projects/sample1/fuse.ts`
If I tried to run this nothing happend, because it didnt find it. 
This is why I added option cwd to GLOB.
Changed the ROOT app since files didnt end up relative to script using sparky.
```
// failing, but dont know why
task("copy-src", async context => {
await src(`./src/**/*.*`)
.dest('./dist3/ts', `/src/`) 
.exec();
});
```
If Ive broken something I dont know atm.
But like I started, we need to add more tests before we merge.
Maybe CI finds something when I create the PR too 😂 
Its late, I need sleep now.
=> fix: sparky path executed in sub folders #1582

src/config/PrivateConfig.ts, src/production/stages/codeSplittingStage.ts, src/utils/__tests__/utils.test.ts, src/utils/utils.ts
Notice `"ngc-browser"`, that is the entry to the project files being compiled. I do think it would be nice to be able to remove "ngc-browser" (or whatever in a given project) by exposing an option in config, or if there is a way to automatically detect this in the fusebox context I am not aware of.
=> fix(code-splitting): pass correct config value + other changes

docs/stylesheet.md, src/config/ILessProps.ts, src/stylesheet/less/lessHandler.ts
I would like to pass options to the less compiler such as { modifyVars: { 'accent-color': 'blue' } }.
I propose to add an options object to stylesheet.less that would be passed to less.render().
=> Add options passed to less compiler.

src/resolver/polyfills.ts
`worker_thread` was missing but makes sense to simply share the collection of node (server) polyfills too.
=> fix: apply all node polyfills to electron

src/production/transformation/conditionUnwrapper.ts
there is problem when .runProd() starting on tslib.es6.js, and other files (even on empty project source files):
```
(node:352) UnhandledPromiseRejectionWarning: TypeError: node.getExpression is not a function
at onIfStatement (G:\source\git\modules\fb\node_modules\fuse-box\production\transformation\conditionUnwrapper.js:75:29)
at Identifiers.forEach.id (G:\source\git\modules\fb\node_modules\fuse-box\production\transformation\conditionUnwrapper.js:114:13)
at Array.forEach (<anonymous>)
at Object.conditionUnwrapperProduction (G:\source\git\modules\fb\node_modules\fuse-box\production\transformation\conditionUnwrapper.js:112:17)
at Object.performStaticTransformations (G:\source\git\modules\fb\node_modules\fuse-box\production\transformation\index.js:11:26)
at staticTransform …
```
=> check if node.getExpression is exists

src/resolver/__tests__/nodeModuleLookup.test.ts, src/resolver/nodeModuleLookup.ts, src/resolver/resolver.ts, src/utils/__tests__/utils.test.ts, src/utils/findUp.ts
All that work, but it ended up being a tiny change.  Also, an insanely difficult bug.
The change is simple, when searching all node_module paths, also check for `node_modules` upwards.
=> fix(resolver): local modules now find root

src/core/Context.ts
This feature adds the functionality to pass plugin options to the transformer:
Simplified example without fallbacks to defaults:
`fuse.ts`
```js
plugins: [
pluginTest({
autoInject: true,
target: /src\/(.*?)\.(js|jsx|ts|tsx)$/
})
],
```
`plugin_test.ts`
```ts
export function pluginTest(opts?: any) {
const { target, ...options } = opts;
return (ctx: Context) => {
ctx.transformerAtPath(target, TestTransformer, options);
};
}
```
`TestTransformer.ts`
```ts
export const TestTransformer = (opts?: any): ITransformer => {
if (opts.autoInject) {
// do something else?
}
}
```
=> feature(plugins): Pass plugin options to corresponding transformer

src/production/transformation/processTransformation.ts
fix #1654
Uses `globalThis` for modern browsers and [this polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#Examples) for those that don't have `globalThis`.
=> fix(production): polyfill global

docs/webIndex.md, src/production/bundle_prod.ts, src/production/main.ts, src/web-index/webIndex.ts
fix #1718
API example:
```html
<!DOCTYPE html>
<html>
<head>
<title>Example</title>
<link rel="icon" href="$import('assets/favicon.png')" />
$css
</head>
<body>
$bundles
</body>
</html>
```
I reused the `resolveCSSResource` function for this which should be fine for now IMO. A unified way of handling assets/resources would be useful for this though.
I tested this feature in my own project and it ended up working quite nicely.
=> feat(web-index): allow HTML template imports

src/compiler/__tests__/__snapshots__/bundle.polyfill.transform.test.ts.snap, src/compiler/transformers/bundle/BundlePolyfillTransformer.ts
process alone wasn't handled, having process.env.NODE_ENV and other shared methods aren't enough. Sometimes users check process, hence we need to make sure it's never undefined
=> fix: added direct process to polyfills

src/moduleResolver/moduleResolver.ts, src/resolver/nodeModuleLookup.ts
Do custom module loading before yarn 2 pnp module loading.
Also, throw a meaningful error if resolution of an injected module fails (instead of "Cannot read property 'id' of undefined")
=> fix: yarn 2 support (can't find fuse-box-hot-reload)

src/compiler/__tests__/__snapshots__/jsx.test.ts.snap, src/compiler/__tests__/jsx.test.ts, src/compiler/transformers/shared/JSXTransformer.ts
Alpha currently transpiles to invalid javascript on the following:
```JSX
function test() {
return <animated.div>1</animated.div>
}
```
The issue appears to be that because "animated" is lower case, it gets transformed into a string literal `"animated"` and then `"div"` is appended like `("animated")."div"`.  But this shouldn't be done on identifiers that are already identified as MemberExpressions.
Confirmed that tsc's transpiler outputs:
```JSX
createElement(animated.div, null, "1")
```
This PR adds a test to match the tsc behavior and fixes the issue.
=> fix: invalid transpile output on lower-case dotted JSX element names

src/resolver/nodeModuleLookup.ts
In a PnP environment you don't want to fall back on node_modules search logic.  If PnP says that a dependency can't be resolved, then it shouldn't be resolved.  PnP is designed to really own module resolution.
PnP is intentionally stricter about loading dependencies.  For example, it won't allow a module in one package to import another package unless the first one has declared the second as a dependency.  Being able to "find" that dependency doesn't matter.  If the environment is PnP and PnP says it can't be resolved, then it shouldn't be resolved.
=> fix: do not fall back to node_modules in a PnP environment, and don't hide PnP errors

docs/watcher.md, src/config/IWatcher.ts, src/watcher/watcher.ts
This is a proposed feature to how watcher is configured.
Chokidar lets you specify one to many "root" paths to watch.  Currently fuse-box watches only one root, which is always `env.APP_ROOT`.  This PR leaves that as the default but allows overriding it with a `root` property in `IWatcherPublicConfig`.
Note that in a monorepo environment relying on workspaces, you would specify those workspace folders as roots, and in a future change, I plan to add the ability to auto-detect if in a workspaces environment and add those automatically.  But manual override of roots is a good feature to have anyway.
=> feat: allow specifying watcher root paths

src/fuseLog/colors.ts, src/hmr/hmr.ts
I.e. when HMR is triggered but no modules are sent, it logs this log message:
This PR changes that to this:
=> fix: correct log messages containing variable == 0 and hmr "module" plural-ification

src/compilerOptions/__tests__/typescriptReferences.test.ts
If a test environment has a package.json above the fuse-box repo root, one of the ts reference tests fails.  This PR fixes the test to ignore those.
=> chore: fix a false test failure in ts references for some setups

src/compiler/__tests__/__snapshots__/require.statement.interceptor.test.ts.snap, src/compiler/__tests__/require.statement.interceptor.test.ts, src/compiler/transformers/bundle/RequireStatementInterceptor.ts
Replaces
`typeof require` to `function`
@wagerfield If you have other additions here please let me know. 
I remember you mentioned that issues on Slack, so there is the fix to it.
=> fix: typeof require operators should be replaced

src/cache/cache.ts, src/moduleResolver/asyncModuleResolver.ts, src/resolver/__tests__/nodeModuleLookup.test.ts, src/resolver/nodeModuleLookup.ts, src/resolver/resolver.ts
OK, Here is my proposed solution for supporting "user-owned" packages other than the "default" package.
Note: sometimes these are called "local" packages or just "not external" packages, but in the code, "local" and "external" can sometimes mean other things.  So I'm using the term "user-owned" to mean "A package that we expect the user to modify".  This is in contrast to packages that are downloaded from a package registry (things in node_modules) that the user should not modify.  I derived the term from `PackageType.USER_PACKAGE` which is already in the code.
Fuse-box already has a package `type` that can be either `USER_PACKAGE` or `EXTERNAL_PACKAGE`.  The `type` determines how the package is treated by the cache.  But currently only the "default" package is ever set to `USER_PACKAGE`. …
=> [Proposed] Auto-detect if Package is "User-Owned" or not

src/utils/__tests__/utils.test.ts, src/utils/utils.ts, src/watcher/watcher.ts
Currently relative root paths don't work in the watcher config.  E.g. the following doesn't work
```javascript
watcher: {
root: "..",
}
```
This PR adds support for relative paths.
=> fix: allow providing relative root for watcher

src/stylesheet/stylus/stylusRenderer.ts
The stylus people changed from `stylus/lib/nodes/Literal.js` to `literal.js`. So one character changed. This PR updates fuse-box stylus renderer to use that file.
Before this PR:
`❌ Cannot find module 'stylus/lib/nodes/Literal'`
After:
=> fix: stylus dependency filename change

src/config/config.ts
**Issue:**
Assets (svg,png,jpg) are not able to load on the web page due to an incomplete url. It shows `/0ea3030a.svg` instead of `/resources/0ea3030a.svg`
**Found bug:**
The `resourcePublicRoot` in `src/plugins/core/plugin_link.ts` stays at `'/'` instead of `'/resources'`
It uses ` ctx.config.link.resourcePublicRoot` from `/config/config.ts`
**Code:**
In `src/config/config.ts` at `getPublicRoot()` the right `/resources` can be found in `self.resources. resourcePublicRoot`. It also looked to me that the `return publicPath` was at the wrong place (should be at the bottom, not after the second if).
This fixed it for all my use-cases where the images were broken. Let me know if this is a decent fix.
Config used:
```js
class Context {
runServer;
getConfig = () =>
fusebox({
target: "browser", …
```
=> Fix missing `/resources` in asset paths

src/stylesheet/sassHandler.ts
fix for issue  **.sass files treated as .scss**  (https://github.com/fuse-box/fuse-box/issues/1834)
=> Fix: SASS indent syntax support

package-lock.json, package.json, src/compilerOptions/compilerOptions.ts, src/compilerOptions/getExtendedTsConfig.ts, src/compilerOptions/tryLoadExtendedTsConfig.ts, src/tsconfig.json, tsconfig.json
In previous version, using fuse-box with tsconfigs and 'extends' was limited to a single level of inheritance. If the 'base' tsconfig also extended, then that third tsconfig wouldn't be taken into account.
Also, extends declared as 'node_modules', e.g. `"extends": "@myorg/tsconfig"` would not be resolved correctly.
This PR adds functionality for both of these scenarios.
=> Fix tsconfig extends

src/bundleRuntime/bundleRuntimeCore.ts
Fixes this issue on IE11 as arrow functions is invalid syntax for ES5 builds:
=> Fix IE11 compatibility with runtime core

src/compilerOptions/tryLoadExtendedTsConfig.ts
Previously, in a monorepo for example, if tsconfig extended another tsconfig file kept in a workspace's node_module directory, then resolve would fail, since it was inspecting from CWD (root) only.
This update adds the local tsconfig file's path to the resolver, so that local node_modules folders are included.
=> fix(tsconfig-loader): tsconfig extends loader wont resolve local module paths

src/bundle/__tests__/bundleRouter.test.ts, src/bundle/bundle.ts, src/bundle/bundleRouter.ts, src/testUtils/integrationTest.ts
Since configuration is already accepting vendor bundles code-splitting, I've prepared a first approach where different vendor bundles are created matching the mapping patterns specified in configuration.
```typescript
bundles: {
app: './app.$hash.js',
mapping: [
{ matching: '@webcomponents*', target: './vendor.webcomponents.$hash.js' },
{ matching: '@material*', target: './vendor.material.$hash.js' },
],
vendor: './vendor.$hash.js',
},
```
With this configuration, we should expect that all `@webcomponents` and all `@material` dependencies be splitted in a `vendor.webcomponents.js` and `vendor.material.js` bundles. 
In `index.html` it should append the following too: 
```html
<script type="text/javascript" src="app.$hash.js"></script>
<script type="text/javascript" …
```
=> Vendor mapping bundles

src/bundle/bundleRouter.ts
hello
splitFileNames is an array so splitFileNames[fileName] will always respond with undefined, use indexOf instead.
My problem was only visible when build on linux, on windows, the relativePath come with "/" as separator, or 'path.sep' is "\" so paths.shift() respond with full path, or in linux 'path.sep' is "/" so paths.shift() respond with "/" and the split works, and becaue of wrong test in the while loop, the function return always the fileName only without path, so that make same name for all my dynamic package (because I remove the hash tag too)
thx
=> fix wrong test of element exist in array

old_docs/getting-started/installation.md, website/versioned_docs/version-3.5.0/getting-started/installation.md, website/versioned_docs/version-3.6.0/getting-started/installation.md, website/versioned_docs/version-3.7.0/getting-started/installation.md
There is a small typo in old_docs/getting-started/installation.md, website/versioned_docs/version-3.5.0/getting-started/installation.md, website/versioned_docs/version-3.6.0/getting-started/installation.md, website/versioned_docs/version-3.7.0/getting-started/installation.md.
Should read `depending` rather than `dependending`.
=> docs: Fix simple typo, dependending -> depending

website/versioned_docs/version-4.0.0/development/full-config.md
So, this is a quick fix. However, it seems there are quite a few inconsistences in docs.
Here's another if anyone's able to address it:
On docs/development/full-config ...
... the hmr link points to 
https://fuse-box.org/docs/development/hmr
However, 1) there is no such property `config.watch` according to the `IPublicConfig`, and 2) there's nothing explicitly about HMR on this page.
=> Correct config.hmr type

src/watcher/watcher.ts
sometimes reaction is fired after reactionStack is empty. so clone stack for reaction.
=> fix: empty reactionStack bug

src/core/build.ts
sometimes additional process needed after bundle completed. so when build first bundle, wait all the events ends.
=> fix: wait for first bundle completed

src/compilerOptions/compilerOptions.ts
compilerOptions.processEnv replaced with env. but sometimes i want to use different env for compiling and running. 
so i changed compilerOptions.processEnv replaced with env when only processEnv not exist.
=> fix: replace processEnv to env when no processEnv

src/bundle/__tests__/bundleRouter.test.ts, src/bundleRuntime/bundleSource.ts, src/moduleResolver/asyncModuleResolver.ts
css module resolving order is so important.
so i made module id same with resolving order and when building css, reordering css modules by module id.
=> fix: css module order bug

src/watcher/watcher.ts
Fixes `TypeError: Cannot read property 'length' of undefined` when fuse-box is started in dev with minimal configuration:
```ts
import { fusebox } from "fuse-box";
const fuse = fusebox({
entry: "../src/index.ts",
target: "browser",
devServer: true,
webIndex: true,
});
fuse.runDev();
```
=> Fix: Watcher when props.root is undefined
